### ISSUE TITLE
PERL module error

### ISSUE THREAD

**Issue by lyd0527** [adigenova/wengan#1]
Hi,

I try to perform `wengan` for hybrid assembly. But I got an error

```
perl wengan.pl -x pacraw -a M -c illu_contig.fa -l pac.fq.gz -p asm1 -t 20 -g 2000
```

 ```
Can't use an undefined value as an ARRAY reference at /home/bio/softwares/wengan/perl/Wengan/Scheduler/Local.pm line 118
```

Could u pls give me some help? Thank you very much.

Best,

Yuanda

**Comment by adigenova** [comment]
Hi Yuanda,
Thanks for trying wengan, but for the moment there is no official release yet and the code that you are using is incomplete. An official release will be available at the end of this week. 
Best,
Alex
