### ISSUE TITLE
Short reads of length 100bp

### ISSUE THREAD

**Issue by mortunco** [adigenova/wengan#10]
I noticed that short reads of length 100 bp result in poor assemblies. I'm assuming this is because of running Minia with k-mer sizes 41, 81, and 121 regardless of the length of short reads.
What is your recommendations for running Wengan with short reads of length 100 bp?

**Comment by adigenova** [comment]
Hi Tunc:
I have not tested wengan with 2x100bp reads. 
### What is your recommendations for running Wengan with short reads of length 100 bp?
you can try abyss with a k-mer size of 75bp, abyss makes better use of the pair-end information.
### What is the insert-size of your reads?
 if they are overlapping you can merge them with flash and then run a minia3 assembly with 41, 81 and 121. In both cases is better to work in the short-read assembly first and then give that assembly to wengan (-c option).

**Comment by mortunco** [comment]
Hi,

Thank you for the rapid response. No, short reads are not overlapping. I will try abbys with kmer size 75 as you suggested. 
What kmer sizes would you suggest for minia assembly?

Cheers,

T.

**Comment by adigenova** [comment]
What kmer sizes would you suggest for minia assembly?
31,51,71,91 
check the script run_minia.pl in the aux_scripts of wengan, which should be easy to modify to the previous k-mers.
you have to change line 27, to the previous k-mers.
``` my @kmers=(41,81,121); ```

best,

Alex

**Comment by mortunco** [comment]
Thank you !
