### ISSUE TITLE
New PacBio BAM input

### ISSUE THREAD

**Issue by billzt** [adigenova/wengan#12]
In the latest PacBio instrument (Sequel II), it only produce a BAM file. Although it could alse be converted to FASTQ using samtools, all the QUAL values are !.

Is such input format also supported? Can I directly use such FASTQ with no QUAL values?

**Comment by adigenova** [comment]
Hi,
You can provide the long-reads in fasta format (compressed or not with gzip). BAM binary format is not supported by Wengan. 
seqtk tool can be used for fastq -> fasta conversion.

Best,
Alex

**Comment by billzt** [comment]
@adigenova Is FASTQ file also OK? As the README uses `pac.fastq.gz` and so on.

**Comment by adigenova** [comment]
Yes, long-read quality values are ignored by Wengan at the moment.
best,

Alex
