### ISSUE TITLE
No clear instruction on installation

### ISSUE THREAD

**Issue by emmannaemeka** [adigenova/wengan#14]
Hello,

There seem to be no clear instruction on how to install this program. Can it be made simpler?

**Comment by adigenova** [comment]
HI, 
The simplest way is to download the Linux pre-compiled binaries from here:

https://github.com/adigenova/wengan/releases/download/0.1/wengan-v0.1-bin-Linux.tar.gz

there is demo repository with detailed instructions here:

https://github.com/adigenova/wengan_demo

best,
Alex

**Comment by emmannaemeka** [comment]
Thanks

Followed this process

export WG=/home/emmanuel/wengan-v0.1-bin-Linux/wengan.pl


qsub wengan.qsub



Error


/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia -in
mucuna.minia_reads.41.txt -kmer-size 41 -abundance-min 2 -out
mucuna.minia.41 -minimizer-size 10 -max-memory 5000 -nb-cores 1 2>
mucuna.minia.41.err > mucuna.minia.41.log

make: *** [mucuna.minia.41.contigs.fa] Error 1




Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by adigenova** [comment]
can you post the content of :

mucuna.minia.41.log and mucuna.minia.41.err

thanks

**Comment by emmannaemeka** [comment]
cat  mucuna.minia.41.err

/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia: /lib64/libstdc++.so.6:
version `GLIBCXX_3.4.21' not found (required by
/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia)

/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia: /lib64/libstdc++.so.6:
version `GLIBCXX_3.4.20' not found (required by
/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia)

/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia: /lib64/libstdc++.so.6:
version `CXXABI_1.3.8' not found (required by
/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia)

/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia: /lib64/libstdc++.so.6:
version `GLIBCXX_3.4.22' not found (required by
/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia)

/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia: /lib64/libstdc++.so.6:
version `CXXABI_1.3.11' not found (required by
/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia)



mucuna.minia.41.log is empty



cat wengan.log

/home/emmanuel/wengan-v0.1-bin-Linux/bin/abyss-pe name=mucuna.abyss2 k=96
B=20G H=4 kc=3 v=-v  np=1 lib="pe1"
pe1="/mnt/data/emmanuel/wengan/MS01_Mucuna_R1_001._paired.fastq.gz
/mnt/data/emmanuel/wengan/MS01_Mucuna_R2_001._paired.fastq.gz" contigs 2>
mucuna.abyss2.err > mucuna.abyss2.log

make: *** [mucuna.abyss2-contigs.fa] Error 2

/home/emmanuel/wengan-v0.1-bin-Linux/bin/minia -in
mucuna.minia_reads.41.txt -kmer-size 41 -abundance-min 2 -out
mucuna.minia.41 -minimizer-size 10 -max-memory 5000 -nb-cores 1 2>
mucuna.minia.41.err > mucuna.minia.41.log

make: *** [mucuna.minia.41.contigs.fa] Error 1






Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by adigenova** [comment]
The problem is that the pre-compiled binaries not found the required GLIB version (`GLIBCXX_3.4.21' not found). So, you have to re-compile from the sources.

the commands should be like this:

#fetch Wengan and its components
git clone --recursive https://github.com/adigenova/wengan.git wengan

for each component, there are specific instructions.

I recommend to start building the WenganM pipeline, it requires the compilation of Minia3, fastmin-sg, intervalmiss, liger and seqtk.   

To compile fastmin-sg, intervalmiss, liger and seqtk, just type "make all" inside each directory.

To compile Minia3 you need CMake.

In the near future, I'm going to provide a conda package for wengan.

Best,
Alex

**Comment by emmannaemeka** [comment]
I don't know what the problem is

intervalmiss]$ make all

mkdir obj

g++   -c -o obj/imopts.o src/imopts.cpp -O3 -std=c++11 -lpthread

g++   -c -o obj/MPCollection.o src/MPCollection.cpp -O3 -std=c++11 -lpthread

g++   -c -o obj/main.o src/main.cpp -O3 -std=c++11 -lpthread

g++   -c -o obj/MPLibrary.o src/MPLibrary.cpp -O3 -std=c++11 -lpthread

g++   -c -o obj/Finterval.o src/Finterval.cpp -O3 -std=c++11 -lpthread

g++   -c -o obj/Contig.o src/Contig.cpp -O3 -std=c++11 -lpthread

g++   -c -o obj/SAMR.o src/SAMR.cpp -O3 -std=c++11 -lpthread

g++  -o intervalmiss obj/imopts.o obj/MPCollection.o obj/main.o
obj/MPLibrary.o obj/Finterval.o obj/Contig.o obj/SAMR.o -O3 -std=c++11
-lpthread

obj/Contig.o: In function `std::vector<std::string,
std::allocator<std::string> > splits<std::string>(std::string const&,
std::string const&)':

Contig.cpp:(.text._Z6splitsISsESt6vectorISsSaISsEERKSsRKT_[_Z6splitsISsESt6vectorISsSaISsEERKSsRKT_]+0x87):
undefined reference to
`std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*,
std::string>, char, std::regex_traits<char>
>::regex_token_iterator(__gnu_cxx::__normal_iterator<char const*,
std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>,
std::basic_regex<char, std::regex_traits<char> > const&, int,
std::bitset<11ul>)'

Contig.cpp:(.text._Z6splitsISsESt6vectorISsSaISsEERKSsRKT_[_Z6splitsISsESt6vectorISsSaISsEERKSsRKT_]+0x94):
undefined reference to
`std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*,
std::string>, char, std::regex_traits<char> >::regex_token_iterator()'

Contig.cpp:(.text._Z6splitsISsESt6vectorISsSaISsEERKSsRKT_[_Z6splitsISsESt6vectorISsSaISsEERKSsRKT_]+0x111):
undefined reference to
`std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*,
std::string>, char, std::regex_traits<char> >::operator++()'

Contig.cpp:(.text._Z6splitsISsESt6vectorISsSaISsEERKSsRKT_[_Z6splitsISsESt6vectorISsSaISsEERKSsRKT_]+0x123):
undefined reference to
`std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*,
std::string>, char, std::regex_traits<char>
>::operator!=(std::regex_token_iterator<__gnu_cxx::__normal_iterator<char
const*, std::string>, char, std::regex_traits<char> > const&)'

Contig.cpp:(.text._Z6splitsISsESt6vectorISsSaISsEERKSsRKT_[_Z6splitsISsESt6vectorISsSaISsEERKSsRKT_]+0x135):
undefined reference to
`std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*,
std::string>, char, std::regex_traits<char> >::operator->()'

collect2: error: ld returned 1 exit status

make: *** [intervalmiss] Error 1



fastmin-sg]$ make all

cc -c -g -Wall -O3   -DHAVE_KALLOC -I ./minimap2 fastmin-sg.c -o
fastmin-sg.o

*fastmin-sg.c:* In function '*revcomp*':

*fastmin-sg.c:94:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for (int i = 0; i < klen>>1; ++i) { // reverse complement sequence

*     ^*

*fastmin-sg.c:94:5:* *note: *use option -std=c99 or -std=gnu99 to compile
your code

*fastmin-sg.c:* In function '*maplongreads*':

*fastmin-sg.c:257:3:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

   for (int i = 0; i < libcount; ++i) headhits[i]=NULL;

*   ^*

*fastmin-sg.c:311:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i< rseq ; i++){ // each kseq_read() call reads one query
sequence

*     ^*

*fastmin-sg.c:313:6:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

      for(int ii=0; ii<libcount; ii++){

*      ^*

*fastmin-sg.c:320:7:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

       for(int l=0; l<max_d; l+=moving_w){

*       ^*

*fastmin-sg.c:388:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for (int f = 0; f < libcount; ++f)

*     ^*

*fastmin-sg.c:411:17:* *error: *conflicting types for '*i*'

     for (size_t i = 0; i < rseq; i++) {

*                 ^*

*fastmin-sg.c:311:13:* *note: *previous definition of '*i*' was here

     for(int i=0; i< rseq ; i++){ // each kseq_read() call reads one query
sequence

*             ^*

*fastmin-sg.c:411:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for (size_t i = 0; i < rseq; i++) {

*     ^*

*fastmin-sg.c:* In function '*map_long_read_files*':

*fastmin-sg.c:465:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i<libcount; i++){

*     ^*

*fastmin-sg.c:488:13:* *error: *redefinition of '*i*'

     for(int i =0; i < alnp->n_threads; ++i) tbuf[i] = mm_tbuf_init();

*             ^*

*fastmin-sg.c:465:13:* *note: *previous definition of '*i*' was here

     for(int i=0; i<libcount; i++){

*             ^*

*fastmin-sg.c:488:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i =0; i < alnp->n_threads; ++i) tbuf[i] = mm_tbuf_init();

*     ^*

*fastmin-sg.c:490:13:* *error: *redefinition of '*i*'

     for(int i=0; i < alnp->n_threads; i++){

*             ^*

*fastmin-sg.c:488:13:* *note: *previous definition of '*i*' was here

     for(int i =0; i < alnp->n_threads; ++i) tbuf[i] = mm_tbuf_init();

*             ^*

*fastmin-sg.c:490:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i < alnp->n_threads; i++){

*     ^*

*fastmin-sg.c:507:13:* *error: *redefinition of '*i*'

     for(int i=0; i< alnp->n_threads; ++i) pthread_join(tid[i], NULL);

*             ^*

*fastmin-sg.c:490:13:* *note: *previous definition of '*i*' was here

     for(int i=0; i < alnp->n_threads; i++){

*             ^*

*fastmin-sg.c:507:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i< alnp->n_threads; ++i) pthread_join(tid[i], NULL);

*     ^*

*fastmin-sg.c:509:13:* *error: *redefinition of '*i*'

     for(int i=0; i<alnp->n_threads; i++) mm_tbuf_destroy(tbuf[i]);

*             ^*

*fastmin-sg.c:507:13:* *note: *previous definition of '*i*' was here

     for(int i=0; i< alnp->n_threads; ++i) pthread_join(tid[i], NULL);

*             ^*

*fastmin-sg.c:509:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i<alnp->n_threads; i++) mm_tbuf_destroy(tbuf[i]);

*     ^*

*fastmin-sg.c:515:13:* *error: *redefinition of '*i*'

     for(int i=0; i<libcount ; i++){

*             ^*

*fastmin-sg.c:509:13:* *note: *previous definition of '*i*' was here

     for(int i=0; i<alnp->n_threads; i++) mm_tbuf_destroy(tbuf[i]);

*             ^*

*fastmin-sg.c:515:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i<libcount ; i++){

*     ^*

*fastmin-sg.c:* In function '*rescue_pair*':

*fastmin-sg.c:532:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i<n_reg; i++){

*     ^*

*fastmin-sg.c:* In function '*mapshortreads*':

*fastmin-sg.c:579:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for (int i = 0; i < libcount; ++i) headhits[i]=NULL;

*     ^*

*fastmin-sg.c:652:13:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

             for(int i=0; i< rseq ; i++){ // each kseq_read() call reads
one query sequence

*             ^*

*fastmin-sg.c:759:13:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

             for (int f = 0; f < libcount; ++f)

*             ^*

*fastmin-sg.c:789:25:* *error: *conflicting types for '*i*'

             for (size_t i = 0; i < rseq; i++) {

*                         ^*

*fastmin-sg.c:652:21:* *note: *previous definition of '*i*' was here

             for(int i=0; i< rseq ; i++){ // each kseq_read() call reads
one query sequence

*                     ^*

*fastmin-sg.c:789:13:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

             for (size_t i = 0; i < rseq; i++) {

*             ^*

*fastmin-sg.c:* In function '*infer_insert_size*':

*fastmin-sg.c:895:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i<1; i++) mm_tbuf_destroy(tbuf[i]);

*     ^*

*fastmin-sg.c:909:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for (int n=beg; n<end+1; n++) {

*     ^*

*fastmin-sg.c:917:14:* *error: *redefinition of '*n*'

     for (int n=beg; n<end+1; n++) {

*              ^*

*fastmin-sg.c:909:14:* *note: *previous definition of '*n*' was here

     for (int n=beg; n<end+1; n++) {

*              ^*

*fastmin-sg.c:917:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for (int n=beg; n<end+1; n++) {

*     ^*

*fastmin-sg.c:* In function '*map_short_read_files*':

*fastmin-sg.c:990:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i =0; i < alnp->n_threads; ++i) tbuf[i] = mm_tbuf_init();

*     ^*

*fastmin-sg.c:992:13:* *error: *redefinition of '*i*'

     for(int i=0; i < alnp->n_threads; i++){

*             ^*

*fastmin-sg.c:990:13:* *note: *previous definition of '*i*' was here

     for(int i =0; i < alnp->n_threads; ++i) tbuf[i] = mm_tbuf_init();

*             ^*

*fastmin-sg.c:992:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i < alnp->n_threads; i++){

*     ^*

*fastmin-sg.c:1011:13:* *error: *redefinition of '*i*'

     for(int i=0; i< alnp->n_threads; ++i) pthread_join(tid[i], NULL);

*             ^*

*fastmin-sg.c:992:13:* *note: *previous definition of '*i*' was here

     for(int i=0; i < alnp->n_threads; i++){

*             ^*

*fastmin-sg.c:1011:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i< alnp->n_threads; ++i) pthread_join(tid[i], NULL);

*     ^*

*fastmin-sg.c:1013:13:* *error: *redefinition of '*i*'

     for(int i=0; i<alnp->n_threads; i++) mm_tbuf_destroy(tbuf[i]);

*             ^*

*fastmin-sg.c:1011:13:* *note: *previous definition of '*i*' was here

     for(int i=0; i< alnp->n_threads; ++i) pthread_join(tid[i], NULL);

*             ^*

*fastmin-sg.c:1013:5:* *error: *'*for*' loop initial declarations are only
allowed in C99 mode

     for(int i=0; i<alnp->n_threads; i++) mm_tbuf_destroy(tbuf[i]);

*     ^*

make: *** [fastmin-sg.o] Error


I don't know if anyone has thesame experiences.



Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by adigenova** [comment]
Can you post the result of:

gcc --version
g++ --version

It seems that you have an old GCC compiler.

best,
Alex

**Comment by emmannaemeka** [comment]
gcc --version

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

Copyright (C) 2015 Free Software Foundation, Inc.

This is free software; see the source for copying conditions.  There is NO

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE



 g++ --version

g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

Copyright (C) 2015 Free Software Foundation, Inc.

This is free software; see the source for copying conditions.  There is NO

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by adigenova** [comment]
Ok, that is the problem , your C++ compiler is old, wengan was compilation was tested with:

with GCC version GCC/7.3.0-2.30 or higher.

So, to solve your issues, I recommend updating your GCC compiler (i.e > 7.)

Best,
Alex

**Comment by emmannaemeka** [comment]
switched to

gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

Copyright (C) 2017 Free Software Foundation, Inc.

This is free software; see the source for copying conditions.  There is NO

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE




but have this error

make: *** No targets specified and no makefile found.  Stop.

Running simple test...

could not find a compiled Minia binary



Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by adigenova** [comment]
Great!!!, for compiling minia you have to run inside the directory:
# compile the code an run a simple test on your computer
cd minia
sh INSTALL

After compilation of all the components listed above, you have to copy them to ${ROOT_WENGAN}/bin.

best,

Alex

**Comment by emmannaemeka** [comment]
Followed this step


cd minia
sh INSTALL

Cloning into 'thirdparty/gatb-core'...

remote: Enumerating objects: 8, done.

remote: Counting objects: 100% (8/8), done.

remote: Compressing objects: 100% (8/8), done.

remote: Total 29368 (delta 0), reused 3 (delta 0), pack-reused 29360

Receiving objects: 100% (29368/29368), 47.96 MiB | 23.36 MiB/s, done.

Resolving deltas: 100% (17999/17999), done.

Submodule path 'thirdparty/gatb-core': checked out
'664696cbc3877d4eb6c3f10f87434efd4c0c83b4'

-- The C compiler identification is GNU 7.3.1

-- The CXX compiler identification is GNU 7.3.1

-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc

-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc --
works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++

-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ --
works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

Git version: 5b131b9

-- gatb-core is here
'/home/emmanuel/wengan/components/minia/thirdparty/gatb-core/gatb-core'

CMake Error at thirdparty/gatb-core/gatb-core/CMakeLists.txt:4
(cmake_minimum_required):

  CMake 3.10.0 or higher is required.  You are running version 2.8.12.2



-- Configuring incomplete, errors occurred!

See also
"/home/emmanuel/wengan/components/minia/build/CMakeFiles/CMakeOutput.log".

make: *** No targets specified and no makefile found.  Stop.

Running simple test...

could not find a compiled Minia binary





And still had same error

**Comment by adigenova** [comment]
The problem now is cmake, check this line in the log that you posted:

## CMake 3.10.0 or higher is required. You are running version 2.8.12.2

update your cmake >= 3.1

best

**Comment by emmannaemeka** [comment]
As a quick fix I installed minia using conda and created a symbolic link in
the wegan/bin folder. This seem to work


Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by adigenova** [comment]
OK, great!!!
