### ISSUE TITLE
wengan M output 

### ISSUE THREAD

**Issue by emmannaemeka** [adigenova/wengan#15]
Hello,
Please which is the final fasta file?

mucuna.GPolished.asm.wengan.fasta
mucuna.SPolished.asm.wengan.fasta

mucuna.Unpolished.asm.wengan.fasta

**Comment by adigenova** [comment]
Hi,
Is mucuna.SPolished.asm.wengan.fasta

Best,
Alex

**Comment by koujiaodahan** [comment]
So,the [Prefix]*.SPolished.asm.wengan.fasta is the final fasta?

> Hi, Is mucuna.SPolished.asm.wengan.fasta Best, Alex
> […](#)
> On 11 Feb 2020, at 19:25, emmannaemeka ***@***.***> wrote: Hello, Please which is the final fasta file? mucuna.GPolished.asm.wengan.fasta mucuna.SPolished.asm.wengan.fasta mucuna.Unpolished.asm.wengan.fasta — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by adigenova** [comment]
yes, the [Prefix].SPolished.asm.wengan.fasta fasta is the final one.
