### ISSUE TITLE
Replacement of hard-coded use of /tmp/

### ISSUE THREAD

**Issue by cabbagesofdoom** [adigenova/wengan#16]
We ran into a problem using WenganD on our HPC when `/tmp/` ran out of space. The problem lines appear to be in `/apps/wengan/0.1/perl/Wengan/Bruijn/Disco.pm`:

```
/apps/wengan/0.1/perl/Wengan/Bruijn/Disco.pm:      my $param="NUM_THREADS=$self->{cores} OUT_DIR=/tmp/$self->{prefix}D";
/apps/wengan/0.1/perl/Wengan/Bruijn/Disco.pm:      "OUT_DIR=/tmp/$self->{prefix}D",
/apps/wengan/0.1/perl/Wengan/Bruijn/Disco.pm:      $cmd="cp -a /tmp/$self->{prefix}D $self->{prefix}D";
```

My sys admin tells me that If `/tmp` is replaced with `$ENV{‘TMPDIR’}` then the problem should not occur.

**Comment by adigenova** [comment]
Hi,
Yes, we hard-coded that directory cause DiscoVar sometimes generates corrupted fasta files on parallel filesystems (i.e Lustre). Meanwhile, you can modify the makefile (prefix.mk) that creates Wengan at your convenience. Then you can run the pipeline with:
``` 
make -f prefix.mk all
```
I'll add a variable to specify the TMPDIR in the next version or as your sys admin suggests by reading it from ```$ENV{TMPDIR}```.

let me know if you need further details to modify the makefile (prefix.mk).

Best,
Alex

**Comment by cabbagesofdoom** [comment]
Thanks. They modified something and made it work - not sure if it was the make or the `Disco.pm` they changed.

**Comment by adigenova** [comment]
Ok, great.
best,
Alex

**Comment by JuliaLopezDelgado** [comment]
Hello.

I am having the same issue with /tmp/ running out of space. How should I specify the location of a /tmp/ file in the prefix.mk file exactly?

Thanks in advance!
Julia

**Comment by zihhuafang** [comment]
Hi @adigenova ,

I am also running into the same issue when running on HPC. However, I use singularity to run Wengan D. Would you suggest to compile the source code by myself following your suggestion (though I would like to create my own tmp as we don't have a lot of space neither with $TMPDIR ), or can I modify something in the container?

Thanks!
Zih-Hua

**Comment by adigenova** [comment]
Hi,
The way to replace the hardcoded /tmp directory is to edit the makefile that wengan generate (prefix.mk),
and then run the pipeline with make -f prefix.mk, there are just two lines to edit:

```
#generate the makefile  (do not forget the -n option):
perl wengan.pl -x ontlon -a D -s EC.50X.R1.fastq.gz,EC.50X.R2.fastq.gz -l EC.ONT.30X.fa.gz -p asm1 -t 20 -g 3000 -n
# edit the file asm1.mk
## original 
asm1.contigs-disco.fa : 
        export MALLOC_PER_THREAD=1
        /Users/adigenova/Git/wengan/bin/DiscovarExp READS="EC.50X.R1.fastq.gz,EC.50X.R2.fastq.gz" OUT_DIR=/tmp/asm1D NUM_THREADS=20 2> asm1.Disco_denovo.err
        cp -a /tmp/asm1D asm1D
        ln -s asm1D/a.final/a.lines.fasta asm1.contigs-disco.fa

## new 
 asm1.contigs-disco.fa : 
        export MALLOC_PER_THREAD=1
        /Users/adigenova/Git/wengan/bin/DiscovarExp READS="EC.50X.R1.fastq.gz,EC.50X.R2.fastq.gz" OUT_DIR=/newtmp/asm1D NUM_THREADS=20 2> asm1.Disco_denovo.err
        cp -a /newtmp/asm1D asm1D
        ln -s asm1D/a.final/a.lines.fasta asm1.contigs-disco.fa
```
Run the pipeline with :

`make -f asm1.mk all
`

best, 
Alex

**Comment by gargkritika** [comment]
Hi 
I am sorry as I am new to singularity, I am not sure of how to access the .mk file. Can you please let me know where this is located?

Thank you
Best regards
Kritika
