### ISSUE TITLE
ligar step failing with error "double free or corruption (out)"

### ISSUE THREAD

**Issue by chrisjackson-pellicle** [adigenova/wengan#17]
Hi,

I'm trying to run WenganD using Nanopore and Illumina data. The assembly gets as far as the liger step, runs for about an hour, and then fails:

`/shared/wengan-v0.1-bin-Linux/bin/liger  --mlp 10000 -t 40 -c  acacia_wengan.MBC1.msplit.fa -l  longreads.acacia_wengan1.fa -d acacia_wengan.MBC1.msplit.cov.txt -p acacia_wengan -s acacia_wengan.sams.txt 2>acacia_wengan.liger.err >acacia_wengan.liger.log`

`make: *** [acacia_wengan.mk:58: acacia_wengan.SPolished.asm.wengan.fasta] Error 134`

A tail of the acacia_wengan.liger.log gives:

> DELETED EDGE ARRAY: EID=15431196493 LQI_S=116457 LQI_E=119473 EID=15431196493 E_S=116456 E_E=119474 5 NLR=4
> DELETED EDGE ARRAY: EID=16083793129 LQI_S=241763 LQI_E=247250 EID=16083793129 E_S=241762 E_E=247251 5 NLR=3
> Total lines examinated 3720
> Total fragments 184228
> Average fragment length 11378
> Total Examinated bases 679058849
> Total Validated bases by at least 1 fragments 674098760
> Percentaje of validated bases  99.2696
> A total of 55 edges were deleted in the validation step
> Time spent in lines validation 4.34629 secs

And the content of acacia_wengan.liger.err is:

> double free or corruption (out)

Can you suggest any way to troubleshoot this issue? WenganA ran without an error on the same data, incidentally.

Thanks very much,

Chris

**Comment by adigenova** [comment]
Hi, 

I have seen this error a couple of times is a bug in the class ValidateBackbone.cpp (segfault happening for looking a position out-of-range in one of the arrays). I have a code that fixes this bug, but I have to commit the new code to the public repo. I'll commit today or tomorrow.  Then, you can compile the liger code and replace the binary of version 0.1. 
A new release that fixes this bug and others is coming (1-2 weeks). 

Best,
Alex

**Comment by adigenova** [comment]
Hi, 
I have committed the code that fix the error. Please use the liger commit 86cccdf (latest).
Best,
Alex

**Comment by chrisjackson-pellicle** [comment]
All fixed, and the run completed successfully. Looks noticeably better than the WenganA run too. 

Thanks very much!

Chris
