### ISSUE TITLE
Can we use wengan to assemble a high heterozygous plant genome?

### ISSUE THREAD

**Issue by xiekunwhy** [adigenova/wengan#19]
Hi Alex,

Can we use wengan to assemble a high heterozygous (1.2% - 2% ) plant genome(genome size is 3-4G, >6G if assembler can not collapse two haplotype correctly)?  Any suggestions about parameters setting if I use wengan to do it?

Best,
Kun

**Comment by adigenova** [comment]
Hi Kun, 

Wengan has not been tested on heterozygous genomes. However, if you share a k-mer spectrum curve of your short-read data, I can provide some ideas of what Wengan parameters to tune. Can you generate a k-mer spectrum (histogram of kmer counts) of your data at k=25 ? and what short-read data do you have (2x150 or 2x250 and coverage)?

Best,
Alex

**Comment by xiekunwhy** [comment]
Please wait one or two days, I will attach kmer spectrum plot at k=25 soon.

**Comment by xiekunwhy** [comment]
Hi Alex，

Here is the kmer plot and hist file got from jellyfish, we all think the only peak in the curve is the heterozygous peak, because the FCM result tell us that the genome size of this species is ~3.2G.

So it is a very high heterozygous genome. Any suggestions about using wengan to assemble such a genome?

Best,
Kun

![25mer hist](https://user-images.githubusercontent.com/17738229/76813656-9de6f080-6833-11ea-85db-7d292a4078de.png)
[25mer.hist.txt](https://github.com/adigenova/wengan/files/4341060/25mer.hist.txt)

**Comment by xiekunwhy** [comment]
Hi Alex,
WenganA was crashed with a Segmentation fault when I assembl this genome, the following are the last several lines of abyss2.err,
Bloom filter FPR: 33.2%
Stats for Bloom filter level 1:
	Bloom size (bits): 85899345920
	Bloom popcount (bits): 84031661483
	Bloom filter FPR: 91.6%
Stats for Bloom filter level 2:
	Bloom size (bits): 85899345920
	Bloom popcount (bits): 77278262341
	Bloom filter FPR: 65.5%
Stats for Bloom filter level 3:
	Bloom size (bits): 85899345920
	Bloom popcount (bits): 65207873300
	Bloom filter FPR: 33.2%
Trimming branches 96 k-mers or shorter
bash: line 1: 105409 Segmentation fault      abyss-stack-size 65536 abyss-bloom-dbg -k96 -q3 --kc=3 -v -b40G -H4 -j35 ***
make[1]: *** [hci.abyss2-1.fa] Error 139

Any suggestions?

Best,
Kun

**Comment by adigenova** [comment]
Hi kun,

Which short-read coverage do you have? and what kind of short-reads (2x100bp, 2x150bp,2x250bp)?. This is important to interpret the kmer-histogram. Usually, in heterozygous genomes, we see two peaks, one happening at half of the average genome coverage (heterozygous k-mers) and a second one happening at the average genome coverage(homozygous k-mers). From your plot, I see only one peak, whit a long tail of high-frequency k-mers(repeats). So, I think that your genome is very repetitive.  I'll take a closer look at the k-mer counts. Please let me know the kind of short-read data that you have.

Best,
Alex

**Comment by adigenova** [comment]
The abyss error seems to be related to the stack-size. You can change the stack-size using the following command:

```
 ulimit -s unlimited
```
you have to put that command before running wengan (i.e previous to the wengan comand in your job script).

best,
Alex

**Comment by xiekunwhy** [comment]
Hi Alex,
Thank you very much.

I can't exactly understand the meaning of "Which short-read coverage", but I can tell you that the short-reads I used to generate k-mer couts is 2x150bp (library insert size is 450bp), ~100X(if genome size is 3.2G). All data I have are listed in the table below, and the first data set was used to generate the k-mer curve at k=25.
And I will try ulimit to run wenganA, and thank you again.
![image](https://user-images.githubusercontent.com/17738229/76848731-28087680-687f-11ea-8c96-c214bd8846d6.png)

Best,
Kun

**Comment by xiekunwhy** [comment]
Hi Alex,
WenganA stopped again even I ran it with unlimit,
`ulimit -s unlimited
/Bio/bin/perl /Bio/Linux-src-files/NGS/Genome_assemblers/wengan/wengan-git/wengan.pl -x ontraw -a A -g 3200 ...`
and the stopped errors were reported like following, any ideas to deal with?
Bloom filter FPR: 33.2%
Stats for Bloom filter level 1:
	Bloom size (bits): 85899345920
	Bloom popcount (bits): 84031661483
	Bloom filter FPR: 91.6%
Stats for Bloom filter level 2:
	Bloom size (bits): 85899345920
	Bloom popcount (bits): 77278262044
	Bloom filter FPR: 65.5%
Stats for Bloom filter level 3:
	Bloom size (bits): 85899345920
	Bloom popcount (bits): 65207872953
	Bloom filter FPR: 33.2%
Trimming branches 96 k-mers or shorter
bash: line 1: 117177 Segmentation fault      abyss-stack-size 65536 abyss-bloom-dbg -k96 -q3 --kc=3 -v -b40G -H4 -j35

Best,
Kun

**Comment by mictadlo** [comment]
Hi,
How is it possible to generate k-mer spectrum curve of my short-read data?

Thank you in advance,

Michal
