### ISSUE TITLE
Problem with wengan-v0.2-bin-Linux versus wengan-v0.1-bin-Linux for CCS reads

### ISSUE THREAD

**Issue by jelber2** [adigenova/wengan#22]
Hi, 

I can run the following using Wengan-v0.1 release

    perl /genetics/elbers/wengan-v0.1-bin-Linux/wengan.pl \
    -x pacccs \
    -a M \
    -s ../wm5_trim_rm_optical_dups_combined_seq_replicates_dedupe_bbduk-k31-speed15-R1.cor.fq.gz,../wm5_trim_rm_optical_dups_combined_seq_replicates_dedupe_bbduk-k31-speed15-R2.cor.fq.gz \
    -l ../wm3-pacbio-subreads-3-icecreamfinder-bbduk-k31-speed15-corrected-with-wm5-lighter-k17-680000000-0.1-bcalm2-k65-abund3-clipped.fastq.gz \
    -c /genetics/fly/genome/denovo/haslr5/sr_k65_a3.contigs.nooverlap.200.fa.gz -g 680 -p clipped > wengan-minia-clipped.log 2>&1 &

But, the updated commands for Wengan-v0.2 release

    perl /genetics/elbers/wengan-v0.2-bin-Linux/wengan.pl \
    -x ccspac \
    -a M \
    -s ../wm5_trim_rm_optical_dups_combined_seq_replicates_dedupe_bbduk-k31-speed15-R1.cor.fq.gz,../wm5_trim_rm_optical_dups_combined_seq_replicates_dedupe_bbduk-k31-speed15-R2.cor.fq.gz \
    -l ../wm3-pacbio-subreads-3-icecreamfinder-bbduk-k31-speed15-corrected-with-wm5-lighter-k17-680000000-0.1-bcalm2-k65-abund3-clipped.fastq.gz \
    -b ../wm3-pacbio-subreads-3-icecreamfinder-bbduk-k31-speed15-corrected-with-wm5-lighter-k17-680000000-0.1-bcalm2-k65-abund3-clipped.fastq.gz \
    -c /genetics/fly/genome/denovo/haslr5/sr_k65_a3.contigs.nooverlap.200.fa.gz -g 680 -p clipped > wengan-minia-clipped.log 2>&1 &

results in 
   
    cat clipped.fms.err

    LOG: Mapping mode =pacccs H=0 k=21 w=10 L=2000 l=250 q=30 m=150 c=65 r=500 t=1 o=FM I=500,1000,2000 s=1
    Building contig index
    [M::mm_idx_gen::1591173570.185*0.00] collected minimizers
    [M::mm_idx_gen::1591173585.914*0.00] sorted minimizers
    [M::mm_mapopt_update::1591173588.800*0.00] mid_occ = 68
    [M::mm_idx_stat] kmer size: 21; skip: 10; is_hpc: 0; #seq: 1040074
    [M::mm_idx_stat::1591173590.686*0.00] distinct minimizers: 100098122 (91.83% are singletons); average occurrences: 1.212; average spacing: 5.703
    Index construction time: 58.593850 seconds for 1040074 target sequence(s)
    gzopen of 'clipped.ccs.ec.fa' failed: No such file or directory.

    cat wengan-minia-clipped.log

    ln -s /genetics/fly/genome/denovo/haslr5/sr_k65_a3.contigs.nooverlap.200.fa.gz clipped.minia.121.contigs.fa
    /genetics/elbers/wengan-v0.2-bin-Linux/bin/seqtk seq -L 200 clipped.minia.121.contigs.fa  | /genetics/elbers/wengan-v0.2-bin-Linux/bin/seqtk seq -l 60 - > clipped.minia.contigs.fa
    grep ">" clipped.minia.contigs.fa | sed 's/km:f://' | awk '{print $1" "$4}' | sed 's/>//g' > clipped.minia.contigs.cov.txt
    /genetics/elbers/wengan-v0.2-bin-Linux/bin/fastmin-sg pacccs -k 21 -w 10 -q 30 -r 500 -I 500,1000,2000  -t 1 clipped.minia.contigs.fa clipped.fms.txt 2>clipped.fms.err >clipped.fms.log
    clipped.mk:15: recipe for target 'clipped1.ccs.I500.fm.sam' failed
    make: *** [clipped1.ccs.I500.fm.sam] Error 1

The makefile does not seem to generate `clipped1.ccs` and `clipped.ccs.ec.fa`

Best,
Jean

**Comment by adigenova** [comment]
Hi Jean, 
Wengan v0.2 does not implement CCS only assemblies, it was an experimental pipeline in v0.1. The "ccspac"  of Wengan v0.2  expects PACBIO HiFi and PacBio CLR reads. Moreover, hybrid assemblies combining ccs with error-prone long reads (ONT, PAC CLR) have been tested only on haploid genomes. In your case is better to use Wengan v0.1.  
From your commands, I can guess that you have short and long reads and that you error corrected the long-reads. Then you are input the corrected long-reads as ccs to Wengan v0.1. If that is the case, try WenganD using the raw pacbio reads (pacraw) and the short-read. WenganD may lead to a better assembly result. If you don't have enough memory, you can try WenganA or WenganM instead. 
The Wengan v0.2 zenodo repository contains assemblies for non-human species, including Fly (link: https://zenodo.org/record/3779515). Wengan achieves N50s > 11Mb for fly using short+ONT reads.
  
Best,
Alex

**Comment by jelber2** [comment]
Thank you. These were not really true CCS reads but those error-corrected with [GraphAligner](https://github.com/maickrau/GraphAligner).
