### ISSUE TITLE
PacBio CCS reads

### ISSUE THREAD

**Issue by dabitz** [adigenova/wengan#23]
Is the option for CCS reads optimized?

**Comment by adigenova** [comment]
Hi,
The previous Wengan version had a ccs-only assembly option, the current version 0.2 can combine CCS plus error-prone long reads (ONT or PAC bio). The latter has been tested on haploid genomes only.  For CCS-only data there are specific assemblers like hifiasm that might be more appropriate.
Best,
Alex
