### ISSUE TITLE
binaries v01 / v02

### ISSUE THREAD

**Issue by LemoAlex** [adigenova/wengan#26]
Hello wengan users,

Are the needed binaries (e.g. abyss-pe, minia, Discovarexp, liger...) from wengan v.02 the same that were used in wengan v.01 ? If yes, can I simply copy paste my bin folder from v.01 to my v.02 ?

Thank you for the help,

Alexandre

**Comment by adigenova** [comment]
Hi Alexandre,
Not all the binaries are the same. The code changed for liger, fastmin-sg, intervalmiss and the Perl code. The binaries of short-read assembler are identical, except for Minia where compiled binary include support for larger k-mers in v0.2 (up to 451bp). Therefore, I do not recommend to copy all the binaries from v0.1 to v0.2. The v0.2 pre-compiled binaries can be donwloaded from the release page. 
Best Alex.

**Comment by LemoAlex** [comment]
Hi Alex,

Thanks a lot, I just got all the binaries from the source code!

Cheers,

Alexandre

**Comment by adigenova** [comment]
Great!
