### ISSUE TITLE
wengan v01 vs v02

### ISSUE THREAD

**Issue by LemoAlex** [adigenova/wengan#27]
Hello Wengan users,

I am currently trying to assemble a genome using ~50X Illumina reads and ~5X PACBio reads. 
I used both wengan v01 and wengan v02, and I find rather interesting differences between the assemblies when using exactly the same dataset. 
The "best" assemblies are obtained with both version when using WenganD. However, I am surprised by the fact that based on statistics alone (obtained through assemblathon), v01 gives fairly better results than v02.  (see attached log files)

Is there a reason for that? Should I still use v02 rather than v01?

Cheers,

Alexandre

[WenganD_V1.txt](https://github.com/adigenova/wengan/files/5391289/WenganD_V1.txt)
[WenganD_V2.txt](https://github.com/adigenova/wengan/files/5391290/WenganD_V2.txt)

**Comment by adigenova** [comment]
Hi Alexandre,

It seem that v01 give you a better assembly result (N50 165 vs 103Kb), but did you change some parameters to accomodate the low long-read coverage (5X)?. You shold probably set the -N  parameter to -N 2. Can you count the number of deleted edges at the  liger step for each assembly ("grep DELETED *liger.log")?. Overall, there are few differents between v01 and v02 involving the WenganD pipeline, thus results might be similar with V02 a bit more accurate.

Best,

Alex

**Comment by LemoAlex** [comment]
Hi,

Thanks for the rapid answer!
 I have 494 (v01) vs 14956 (v02) deleted edges (grep DELETED *.ligerlog | wc -l) for each assembly. So I guess I am loosing quite a lot of information in v02 here?
Indeed, I had -N 2 for the v01 but not for the v02. I am running v02 again with the N parameter included this time. I will let you know the results when it's finished, in a couple of days probably.

Cheers,
Alexandre

**Comment by LemoAlex** [comment]
Hi,
Some updates, as promised. Indeed, when adding the -N 2 parameters, results are extremely similar between v01 and v02, even though some slight differences appear.

Thanks a lot!

Alexandre

[Wengan_D_V2_N2.log](https://github.com/adigenova/wengan/files/5407263/Wengan_D_V2_N2.log)

**Comment by adigenova** [comment]
Great!
Best,

Alex
