### ISSUE TITLE
Output file details?

### ISSUE THREAD

**Issue by Dikaryotic** [adigenova/wengan#3]
Hiya, 

Could you give some info regarding the output files? I notice a GPolish and an SPolish, but what's the difference? 

Cheers

**Comment by adigenova** [comment]
Hi, 
The final assembly output is the SPolish file, Gpolish is an intermediate file. Wengan implements two polishing modes, one graph-based (Gpolished), and a second one based on sequence alignments (SPolished).  Gpolished is applied before SPolish. I'll provide soon a tutorial.
Best,
Alex
