### ISSUE TITLE
Evaluate the assembly results

### ISSUE THREAD

**Issue by koujiaodahan** [adigenova/wengan#30]
HI， I have got the  assembly results of a human by wengan,and  i want to assess the [Prefix].SPolished.asm.wengan.fasta by running  Quast , so  could you play the running quast command line used in your article?

**Comment by adigenova** [comment]
Hi, 

In the revised version that is going to be published, we used quast as follows:
```
quast -r GRCh38_chrom_no_alt.fa --large --no-icarus --no-html  --min-identity 80  --fragmented  -o quast-result wengan.asm.fa
```
The GRCh38 reference contains only autosomes + sexual chromosomes (no alt). 

Best,
Alex

**Comment by koujiaodahan** [comment]
thanks, if  the sample is human ,  should i  run ./quast-lg.py instead of quast.py？

**Comment by adigenova** [comment]
The --large option, enable quast-lg.

Best
Alex

**Comment by koujiaodahan** [comment]
command as the follow?
quast --large -r GRCh38_chrom_no_alt.fa --large --no-icarus --no-html  --min-identity 80  --fragmented  -o quast-result wengan.asm.fa

**Comment by adigenova** [comment]
yes, but you are including two times the --large option, so should be like this:
```
quast -r GRCh38_chrom_no_alt.fa --large --no-icarus --no-html --min-identity 80 --fragmented -o quast-result wengan.asm.fa
```
