### ISSUE TITLE
Problem running Wengan with singularity

### ISSUE THREAD

**Issue by brookshenry3** [adigenova/wengan#32]
Hi,

I originally tried building Wengan from source as suggested however after running into many of the same issues as issue #14 (and following many of the suggested fixes with no luck) I decided to switch to running Wengan using singularity. I ran the following command: 

    singularity exec $CONTAINER perl ${WENGAN} \
     -x ontraw \
     -a M \
     -s ecoli/reads/EC.50X.R1.fastq.gz,ecoli/reads/EC.50X.R2.fastq.gz \
     -l ecoli/reads/EC.ONT.30X.fa.gz \
     -p wengan_output/ec_Wm_or1 -t 10 -g 5

However I got this output in my error file:

    perl: warning: Setting locale failed.
    perl: warning: Please check that your locale settings:
	    LANGUAGE = (unset),
	    LC_ALL = (unset),
	    LANG = "en_US.UTF-8"
        are supported and installed on your system.
    perl: warning: Falling back to the standard locale ("C").
    make: *** [wengan_output/ec_Wm_or1.minia.41.contigs.fa] Error 1

And this for output in `ec_Wm_or1.minia.41.err`:

HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Fint.c line 1087 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5G.c line 454 in H5Gopen2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5G.c line 287 in H5Gcreate2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5L.c line 813 in H5Lexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5D.c line 165 in H5Dcreate2(): not a location ID
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5D.c line 460 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 883 in H5Sget_simple_extent_dims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 392 in H5Sclose(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 401 in H5Aopen(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 677 in H5Aget_space(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 883 in H5Sget_simple_extent_dims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
  #000: /home/adigenova/HSCAFF/HUMAN/CHM13/HIFI/20kb/minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 634 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
EXCEPTION: Unable to open bank 'wengan_output/ec_Wm_or1.minia_reads.41.txt' (if it is a list of files, perhaps some of the files inside don't exist)

This is my first time using Singularity so apologies in advance if my issue is something trivial.

Thanks in advance for any help/suggestions, I'm happy to provide additional information as needed!

**Comment by adigenova** [comment]
Hi, 
The problem seems to be related to the prefix for output (-p), wengan do not support file directories as part of the prefix. So your line should be :
```
singularity exec $CONTAINER perl ${WENGAN} \
 -x ontraw \
 -a M \
 -s ecoli/reads/EC.50X.R1.fastq.gz,ecoli/reads/EC.50X.R2.fastq.gz \
 -l ecoli/reads/EC.ONT.30X.fa.gz \
 -p ec_Wm_or1 -t 10 -g 5
```

best,
Alex

**Comment by brookshenry3** [comment]
Perfect thank you that solved the issue, I appreciate it!

**Comment by 000generic** [comment]
Hi! I have a potentially similar issue but the above solution isn't clear to me in my case:

I get the following error message:

**Salk :) bash 001-wengan-pacbio
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

  Usage example :
    # Assembling Oxford nanopore and illumina reads with WenganM
    wengan.pl -x ontraw -a M -s lib1.fwd.fastq.gz,lib1.rev.fastq.gz -l ont.fastq.gz -p asm1 -t 20 -g 3000**

And my script looks like this - similar error message but I've commented out things to just running the software and it throws the error.

```
#using singularity
#CONTAINER=/path_to_container/wengan_v0.2.sif
CONTAINER=/home/eedsinger/software/wengan/wengan-v0.2.simg

#location of wengan in the container
WENGAN=/wengan/wengan-v0.2-bin-Linux/wengan.pl

#run WenganM with singularity exec
singularity exec $CONTAINER perl ${WENGAN} \
 #-x pacraw \
 #-a D \
 #-s all-illumina-tube-FCHTTTCCXY_1.fastq,all-illumina-tube-FCHTTTCCXY_2.fastq \
 #-l all-pacbio-SRR17822300-SRR17822301-SRR17944411-SRR17944412-SRR17944413-SRR17952619.fastq \
 #-p wegnan-pacbio -t 60 -g 3000

```
If I uncomment the -x etc I get the following error:

**Salk :) bash 001-wengan-pacbio
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
ERROR: read file all-illumina-tube-FCHTTTCCXY_1.fastq don't exist or have 0 size.**

Not sure what I need to do - I downloaded the software today - and running things a Debian machine with following specs:

**Linux chi 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64
chi is  runs Debian Buster v10.X.
CPU Count: 64 : "GenuineIntel Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz (2 chips x 16 cores : 32 hyperthread cores)"**

Any ideas or suggestions would be greatly appreciated!

Thank you very much,
Eric
