### ISSUE TITLE
ERROR: read file don't exist or have 0 size

### ISSUE THREAD

**Issue by brookshenry3** [adigenova/wengan#34]
Hi there,

I am running Wengan using singularity on our institute's cluster using the following submission script (note path names generalized for privacy):

    #! /bin/bash

    #BSUB -n 10
    #BSUB -W 250:00
    #BSUB -R "rusage[mem=50GB]"
    #BSUB -e error_file%J
    #BSUB -J job_name

    module load htslib/1.4.1
    module load gcc/10.2.0
    module load perl/5.24.1

    #using singularity
    CONTAINER=/home/k001y/programs/wengan_v0.2.sif

    #location of wengan in the container
    WENGAN=/wengan/wengan-v0.2-bin-Linux/wengan.pl

    #Setting location of illumina short read fastq files 
    SHORT_READ=/path/to/short/read/fastas

    #Setting location of ONT raw reads
    LONG_READ=/path/to/long/read/fastas

    #run WenganM with singularity exec
    singularity exec $CONTAINER perl ${WENGAN} \
     -x ontraw \
     -a M \
     -s ${SHORT_READ}/R1.fastq.gz,${SHORT_READ}/R2.fastq.gz \
     -l ${LONG_READ}/longread.merged.fastq \
     -p sample -t 10 -g 5

However I keep on getting the following error:

    ERROR: read file 
    /path/to/short/read/fastas/R1.fastq.gz don't exist or have 0 size.

I've double checked and the paths and file names are indeed correct, so I don't know why I am getting this error. 
The short read and long read fastq files are both in different places, do the files themselves need to be in the same directory or subdirectory as the submission script? I tried creating symlinks to the data in a folder where I was executing Wengan but that didn't seem to help. Unfortunately the files are too large to copy or move into the execution directory. Am I doing something else wrong here?

Thanks in advance for your help!

**Comment by adigenova** [comment]
Hi, 

This error is because singularity doesn't mount the directories where the reads are stored, you have to specify them while calling singularity, for instance:
```
singularity exec  -B /beegfs:/beegfs  $CONTAINER perl ${WENGAN} ...
```
usually is only necessary to specify the first directory (i.e /home/aaa/bbb  -B will be  -B /home:/home).

You can check with the shell command, which gives you a shell inside the container:
```
singularity shell -B /beegfs:/beegfs $CONTAINER
```
if you see the files inside the container, then the paths that you specify with the -B option are OK.

Best,

Alex

**Comment by brookshenry3** [comment]
Great thank you so much for your help, I appreciate it!
