### ISSUE TITLE
Could you give some advice for assembly a 2G sized genome with 60X Pacbio and 60 X illumina data?

### ISSUE THREAD

**Issue by bioinformaticspcj** [adigenova/wengan#35]
Dear the authors:

Thanks very much for devoloping such a useful program and it facilitates my research a lot. Now I have some questions. 
I am tring to assembly a 2G sized genome with 60 X Pacbio and 60X illumina reads, using defualt arguments just results a draft genome with Ng50 8,401,827 bp. I then changed the arguments to "-k 15 -m 100 -N 3 -f 0.12 -M 500", but it has taken more than 10 days to be fihished with 150 Intel(R) Xeon(R) Platinum 8160H CPUs, I do not know when it will be finished. Could you give me some advice for improving the assembly with shorter time.

Thanks again.
looking forward to your timely help.

**Comment by adigenova** [comment]
Hi, 
Nice to know that Wengan is helping with your genome. There are several parameters that can be tuned. I recommend the following:

1. Use WenganD ("-x pacraw -a D") if you have a high memory machine (~400Gb).
2. The default insert-size list for pacbio CLR reads is :
   "-i  500,1000,2000,3000,4000,5000,6000,7000,8000,10000,15000,20000"   if your reads are longer (N10 > 50kb, ie 10% of your reads are longer than 50kb) you should try 
  "-i 500,1000,2000,3000,4000,5000,6000,7000,8000,10000,15000,20000,30000,40000,50000,60000" that will increase the power to solve repeats.
3. The arguments that you modified, I recommend to set them as  "-m 100 -N 3 -f 0.12 -d 5" and leave the other ones as default. The mapping of CLR reads use homopolymer compressed k-mers, so changing the k-mer size will have little impact and might increase the running time (as you are already experiencing).

I think that with the above tunning you should be able to get a better Wengan result. I plan to improve the optimal set of parameters in a genome base way in the near future.

Best,
Alex

**Comment by bioinformaticspcj** [comment]
Dear Alex:
Thanks a lot for your valuable advice. I have now achieved a 16.3Mbp N50 for my genome assembly. But I still have a question that why the assembly seems a little smaller in size than I estimated by Kmer analysis.
The parameters I used are as follows:
&nbsp;wengan.pl -x pacraw -a D -c&nbsp;yinhuang.contigs-disco.fa&nbsp;&nbsp;-i 500,1000,2000,3000,4000,5000,6000,7000,8000,10000,15000,20000,30000,40000,50000,60000
-m 40 -d 5 -N 3 -P 8000&nbsp;


Could you give me some other advice?&nbsp;


Thanks again.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adigenova/wengan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 上午7:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adigenova/wengan] Could you give some advice for assembly a 2G sized genome with 60X Pacbio and 60 X illumina data? (#35)





 
Closed #35.
