### ISSUE TITLE
How to set up -g parameter ?

### ISSUE THREAD

**Issue by ShaolinXU** [adigenova/wengan#36]
Dear author,

I'm very happy with the result from wengan!

- However, I'm a little worry about the `-g` parameter
- We have to set this parameter in each execution, but how strong will this parameter effect our result?
- The genome size estimation of my target animal is 106 Mb from genomescope (using NGS data). Unfortunately, there are some contamination in my nanopore data, so the "genome size" of my nanopore dataset is more likely larger than 106 Mb.
- In such case, how should I set up the `-g` parameter? 

Looking forward your answer!

Best
Shaolin

**Comment by adigenova** [comment]
Hi Shaolin, 
Glad that wengan generated good results for your genome. The genome size parameter is just for setting the size of minimizers while mapping short and long reads. Wengan divides the genome size into three groups, small (<10Mb), medium  (>=10 and <500 Mb), and large (>500 Mb) genome size.  Thus, exact genome size is not really needed and you can set the genome size as `-g 100`. Additionally. issue  #35 provides some ideas to further improve wengan assemblies. 

Best,
Alex

**Comment by ShaolinXU** [comment]
Hi Alex,

Thanks a lot for your quick answer. Now I don't worry about the -g parameter anymore

I'm also trying your suggestion in #35, I will make some feedbacks here to show how this parameter tuning affect my result, compared to the default parameter setting

Best
Shaolin

**Comment by adigenova** [comment]
Feel free to reopen to share your experiments.

Best,
Alex
