### ISSUE TITLE
Reading long-read FASTA input, using 10x chromium linked-read information

### ISSUE THREAD

**Issue by andreaswallberg** [adigenova/wengan#4]
Dear @adigenova 

Thank you for making this software available to the community. It looks stunning and the Perl code is a pleasure to read!

I have a feature request. Is it technically possible to perform the assembly from long-reads without using the associated quality scores in the fastq files? In such a case, could you consider implementing a FASTA reader for the long-reads as well?

This could help in testing, simulations or evaluating the effect of various external read polishers (although I understand that polishing is not necessary for this pipeline itself).

Just a thought, would it be possible incorporate and leverage 10x chromium linked-read information into the assembler? (I notice that one of the assembly options is using Abyss, which can perform some error-correction with 10x info with Tigmint, so this might be indirectly possible)

**Comment by adigenova** [comment]
Dear Andreas,
Thanks for your positive comments.

The long-reads can be provided in FASTA/FASTQ format.  Whit regards to the 10X data, we are working in a 10X scaffolder to combine 10X and long-reads, the pipeline starts assembling the 10X reads, then use the long-reads to create longer contigs and finally use the 10X barcodes to create chromosome-scale scaffolds. If all goes well, we will release the code in January.

Best,
 
Alex

**Comment by andreaswallberg** [comment]
Sounds great!
