### ISSUE TITLE
How to combine mate-pair reads?

### ISSUE THREAD

**Issue by minky** [adigenova/wengan#41]
Hi Alex,

Is it possible to combine information from mate-pair reads in a Wengan run, for example, using Fast-SG? I'm asking because I saw the contig N50 could still be increased after following steps of scaffolding and gapclosing (The contigs were based on ~220X  paired-end + ~20X PacBio data, and I added mate-pair reads using Platanus assembler for scaffolding+gapclosing). 

Ps: Thanks for your previous suggestions. I ran WenganD mode with adjusted the parameters ("-N 3 -P 8000 -L 1000 -Q 1000 -i 500,1000,2000,3000,4000,5000,6000,7000,8000,9000,10000,11000,12000,13000,14000,15000,20000"). Now the contig N50 has increased to ~400k !  :-)

Best,
Minky

**Comment by adigenova** [comment]
Hi Minky, 

Nice that the tuning resulted in a better assembly. It is not possible to include mate-pair libraries into Wengan. However, you can scaffold your wengan assembly (N50 400Kb) using Fast-SG+scaffmatch and your mate-pair data. After you can try to fill the gaps with gapclosing. Therefore this is similar to what you have already done with platanus but starting from Wengan instead.  

Best,
Alex
