### ISSUE TITLE
Why the assembly size is smaller than expected?

### ISSUE THREAD

**Issue by bioinformaticspcj** [adigenova/wengan#44]
Dear the authors:
Thanks a lot for your valuable advice. I have now achieved a 16.3Mbp N50 for my genome assembly. But I still have a question that why the assembly seems a little smaller in size than I estimated by Kmer analysis.
The parameters I used are as follows:
 wengan.pl -x pacraw -a D -c yinhuang.contigs-disco.fa  -i 500,1000,2000,3000,4000,5000,6000,7000,8000,10000,15000,20000,30000,40000,50000,60000
-m 40 -d 5 -N 3 -P 8000

Could you give me some more advice?

Thanks again.

Best wishes.

**Comment by adigenova** [comment]
Hi, 
Nice that the parameters help you to improve the assembly. Regarding the genome size, can you tell me which is the estimated (k-mer) and the genome size assembled by Wengan?. 

thanks!

Best,
Alex

**Comment by bioinformaticspcj** [comment]
Hi Alex,


I estimated the genome size by (17-mer), results show it is 1.62Gb. But, the wengan assembly is&nbsp;1.56Gb.&nbsp;


Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adigenova/wengan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 上午7:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adigenova/wengan] Why the assembly size is smaller than expected? (#44)





 
Hi,
 Nice that the parameters help you to improve the assembly. Regarding the genome size, can you tell me which is the estimated (k-mer) and the genome size assembled by Wengan?.
 
thanks!
 
Best,
 Alex

**Comment by adigenova** [comment]
Hi, 

It seems that the difference in size is in the expected range (~60Mb). These should be sequences related to repeats, centromeres, or large segmental duplications that are still hard to assemble for most assemblers (including Wengan).
So, I do not have feedback to provide this time.

Best,
Alex
