### ISSUE TITLE
A liger error was reproted, need help!

### ISSUE THREAD

**Issue by bioinformaticspcj** [adigenova/wengan#45]
Dear the authors,
Thanks for your valuable previous advice. Wengan is a very cost effective assembler, although may lost some repeats. When trying to assemly a genome sized near 4Gb , I met a problem. The liger software reproted:

"src/BFilling.cpp:73: BFilling::BFilling(GraphS*, std::__cxx11::string, std::__cxx11::string): Assertion `lorder.size() == longreadDB->getTotalseqs()' failed." 

and stoped. 
I do not know why it occured. The parameters used are as follows:
perl wengan.pl -x pacraw -a D -c contigs-disco.fa -s "LAB2020188-a_L2_184184.R1.fastq.gz,LAB2020188-a_L2_184184.R2.fastq.gz,LAB2020188-a_L4_183183.R1.fastq.gz,LAB2020188-a_L4_183183.R2.fastq.gz" -l "m64064_200806_090946.subreads.bam.fq.gz,m64065_200814_093113.subreads.bam.fq.gz,m64066_200810_083047.subreads.bam.fq.gz,m64066_200811_145542.subreads.bam.fq.gz"  -t 60 -g 4000 -i 500,1000,2000,3000,4000,5000,6000,7000,8000,10000,15000,20000,30000,40000,50000,60000,70000,80000 -m 100 -d 5 -N 3 -P 20000 -M 2500

Looking forward to your timely help!

Thanks a lot!

Best,

**Comment by adigenova** [comment]
Hi Bob, 
This problem happens when the long-read data is specified in multiple files, Wengan only expects a single compressed long-read fastq file. I'll improve this in the next version. Hence, you have to merge your long-read files into a single one.

Best,
Alex

**Comment by bioinformaticspcj** [comment]
Thanks Alex, I will merge them together.
