### ISSUE TITLE
Need help for assemblying a high heterozygous genome!

### ISSUE THREAD

**Issue by bioinformaticspcj** [adigenova/wengan#46]
Hi Alex,
I have tried to assembly the ~4G genome, but found it can not be assemblied well with N50 only 275,951 bp and 2.77G in size. I estimated the genome with 17-mers, the results show it is a high heterozygous genome with 0.9% of heterozygosity.

The distribution of the 17-mers is as follows:

![image](https://user-images.githubusercontent.com/38041153/117091862-353c3980-ad8f-11eb-8ec9-18327bc2f73f.png)

Could you give me some advice for parameters setting ?

Thanks a lot.

Best,
Bob

**Comment by adigenova** [comment]
Hi bob, 
Can you start the k-mer histogram from at least 10 of frequency? to see the peaks. A thing that you can do is to generate a short-read assembly with the Platanus assembler that is designed for highly heterozygous genomes (http://platanus.bio.titech.ac.jp/platanus/platanus-allee-2-0-was-released), then give that result as input to Wengan (-c option).

best,
Alex

**Comment by bioinformaticspcj** [comment]
Hi Alex,
Thanks very much for your timely advice. Given platanus is a memory greedy assembler, I am afraid it could not deal with such a big genome using our limited memory (~1Tb). The followed file is the distribution of 17mers altered as you suggested.
[kmer_hist.pdf](https://github.com/adigenova/wengan/files/6446908/kmer_hist.pdf)

Do you have any other advice?

Best,
Bob

**Comment by adigenova** [comment]
Hi bob,

I think that if you feed only 50-60X coverage to Platanus the assembly might fit in 1TB machine. 
There are other alternatives but are more complex to implement, so I suggest starting with Platanus first.

Best
Alex
