### ISSUE TITLE
short read assembly only

### ISSUE THREAD

**Issue by carollia** [adigenova/wengan#48]
Hi,

I only have short read data for my assembly which Wengan seems to do but I don't know what to put in the -l flag since I don't have long reads. What is the suggested command if one doesn't have long read sequence?

Thanks!

**Comment by adigenova** [comment]
Hi carollia,

Wengan is an hybrid assembly, hence short and long-read data are needed. You can create a dummy file called long-reads.fastq.gz and provide that file to Wengan, but then it will crash after completing the initial short-read assembly stage.
Perhaps, a better idea is to use directly DiscovarDenovo which is one of the short-read assemblers that Wengan employs and produce the best results with short-read data.

Best,
Alex

**Comment by adigenova** [comment]
Feel free to reopen if you have further questions!.
Best,
Alex
