### ISSUE TITLE
liger maxpos Assertion error

### ISSUE THREAD

**Issue by alexweisberg** [adigenova/wengan#49]
Hi, thanks for releasing this software, it looks to be very useful. I tried running WENGAN on my dataset with the following options:

perl ./wengan-v0.2-bin-Linux/wengan.pl -x ontraw -a A -s ../illumina/SRR8327096_1.fastq.gz,../illumina/SRR8327096_2.fastq.gz -l ../nanoporecombined.fastq.gz -p asm1 -t 10 -g 60

It seems to run most of the way through, however it dies at an error in the liger step. The asm1.liger.log contains:
Sorting libs by insert size:
asm11.I500.fm.sam 0 476 47
asm11.I1000.fm.sam 1 937 93
asm11.I2000.fm.sam 2 1788 178
asm11.I3000.fm.sam 3 2598 259
asm11.I4000.fm.sam 4 3593 359
asm11.I15000.fm.sam 5 3694 369
asm11.I10000.fm.sam 6 3870 387
asm11.I5000.fm.sam 7 4387 438
asm11.I6000.fm.sam 8 5100 510
asm11.I8000.fm.sam 9 5140 514
asm11.I7000.fm.sam 10 5470 547
asm11.I20000.fm.sam 11 20000 2000
asm11.I30000.fm.sam 12 30000 3000
asm11.I40000.fm.sam 13 40000 4000
asm11.I50000.fm.sam 14 50000 5000
Max allowed coverage 4112.09
AVG:2741.39 STD:4005.75 Limit: 4112.09 #REP(ctg):8
Number of BCC: 46
STARTING TRANSITIVE REDUCTION:
A total of 1 edges can be reduced, the total weight is 1845 ,whit a total lengh of 2614 bases
NO paths founds for edge: 36 245638 1845 2614 12 NODES(e): 370 505
Number of iterations in edge reduction: 3
REDUCED GRAPH 3198 ORIGINAL GRAPH 3198
ENDING TRANSITIVE REDUCTION
Matching Done
Total Edges :2940 input M 2 Edges in matching: 2 MCW: 7714 Total W:7714 % 1
the graph has cicles and we should remove some edges
Deleting edge: 5 4 1845 855
Matching COVER GRAPH 259 ORIGINAL GRAPH 3198
Number of CC 257
Number of CC 257
Total Reduced edges >= 10000 (bp) = 0
A total of 0 (-nan%) reduced edges were converted to fragments
The Physical Coverage represented in the Paths is: -nan
Scaffolds length larger than >= 10000 = 0
Max scaffold length =0

while asm1.liger.err contains:
liger: src/ValidateBackbone.cpp:112: int ValidateBackbone::validate_backbone(int, int, GraphS*): Assertion `maxpos > 0 and maxpos < cov.size()' failed.

**Comment by adigenova** [comment]
Hi Alex, 
The error happens because no scaffolds are produced (Max scaffold length = 0) in an internal step. 
What is the long-read coverage that you have?

Best,
Alex

**Comment by alexweisberg** [comment]
Hi,

That is odd. I have roughly 20x long read coverage of a ~60 Mb genome. I have done a few long read-only assemblies of this dataset with Flye and Canu, which produced ok assemblies (500-700 contigs, N50 ~350kb). The long read input file to Wengan is a concatenated fastq.gz file from three Nanopore flongle runs.

Best,
Alex
