### ISSUE TITLE
Need help for assemblying a high heterozygous genome with platanus2

### ISSUE THREAD

**Issue by bioinformaticspcj** [adigenova/wengan#50]
Hic Alex,
I have tried platanus2 for assemblying the genome, but found it not powerful enough. The results show the raw assembly is very fragmented with contig N50 only 507 bp. When I fed wengan with the contig assembly, it can only assemly ~2G genome (the estimated size is ~4G). 
The command used by  platanus2 are as follows:
platanus_allee assemble -u 0.2 -m 800 -k 29

Could you give me some more suggestions?
Thanks

Best,
Bob

**Comment by adigenova** [comment]
Hi Bob, 

I think that Platanus use multiple k-mers starting from small to large K.
If you do a genome assembly at k=29 it would be extremely fragmented, can you check that Platanus is running properly? 
I know that early Platanus versions used k  up to 161 bp (or larger).

Best,
Alex

**Comment by bioinformaticspcj** [comment]
Hi Alex,

I have checked the log file. Platanus used 29 as the initial K, and used larger K after.
The log information are as follows:
 
KMER_EXTENSION:
K=29, KMER_COVERAGE=56.3062 (>= 4), COVERAGE_CUTOFF=4
K=49, KMER_COVERAGE=47.01, COVERAGE_CUTOFF=4, PROB_SPLIT=10e-14.8406
K=69, KMER_COVERAGE=37.7139, COVERAGE_CUTOFF=4, PROB_SPLIT=10e-11.0704
K=86, KMER_COVERAGE=29.8121, COVERAGE_CUTOFF=2, PROB_SPLIT=10e-10.2033
K=89, KMER_COVERAGE=28.4177, COVERAGE_CUTOFF=2, PROB_SPLIT=10e-10.271
K=91, KMER_COVERAGE=27.4881, COVERAGE_CUTOFF=2, PROB_SPLIT=10e-10.0061

It seems the programe ran properly. Should I use larger K (like > 129 ) to run it again?

Best,
Bob

**Comment by bioinformaticspcj** [comment]
Hi Alex,


I have checked the log file. Platanus used 29 as the initial K, and used larger K after.
The log information are as follows:
&nbsp;
KMER_EXTENSION:
K=29, KMER_COVERAGE=56.3062 (&gt;= 4), COVERAGE_CUTOFF=4
K=49, KMER_COVERAGE=47.01, COVERAGE_CUTOFF=4, PROB_SPLIT=10e-14.8406
K=69, KMER_COVERAGE=37.7139, COVERAGE_CUTOFF=4, PROB_SPLIT=10e-11.0704
K=86, KMER_COVERAGE=29.8121, COVERAGE_CUTOFF=2, PROB_SPLIT=10e-10.2033
K=89, KMER_COVERAGE=28.4177, COVERAGE_CUTOFF=2, PROB_SPLIT=10e-10.271
K=91, KMER_COVERAGE=27.4881, COVERAGE_CUTOFF=2, PROB_SPLIT=10e-10.0061


It seems the programe ran properly. Should I use larger K (like &gt; 129 ) to run it again?


Best,
Bob





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adigenova/wengan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月10日(星期六) 晚上11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adigenova/wengan] Need help for assemblying a high heterozygous genome with platanus2 (#50)





 
Hi Bob,
 
I think that Platanus use multiple k-mers starting from small to large K.
 If you do a genome assembly at k=29 it would be extremely fragmented, can you check that Platanus is running properly?
 I know that early Platanus versions used k  up to 161 bp (or larger).
 
Best,
 Alex

**Comment by adigenova** [comment]
Hi Bob, 
According to the platanus_allele documentation, it define the k-mer sizes as following:
    -k INT               : initial k-mer size (default 32)
    -K FLOAT             : maximum-k-mer factor (maximum-k = FLOAT*read-length, default  0.5)

if your reads are 151bp, perhaps a -K 0.9 would be better, but I'm afraid that this will not make a big difference relative to the current result that you have, but perhaps is worth trying. Another option is to start with the long-reads, perhaps using the flye assembler, and then purge the heterozygous contigs with [purge_dups](https://github.com/dfguan/purge_dups) or [hapSolo](https://github.com/esolares/HapSolo). Starting with the long-reads might be advantageous as longer read overlap can be computed and therefore more bubbles (main graph pattern found in heterozygous genomes) can be spanned.
 Unfortunately,  Wengan is not well suited for highly heterozygous genomes and is a thing that I plan to work in but in the future (next year).  


Best,
Alex

**Comment by bioinformaticspcj** [comment]
Hi Alex,


Thanks a lot for your timely and valuable advice and I will try as you suggested. Also, I am looking forward to the next version of wengan.


Best,
Bob




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adigenova/wengan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adigenova/wengan] Need help for assemblying a high heterozygous genome with platanus2 (#50)





 
Hi Bob,
 According to the platanus_allele documentation, it define the k-mer sizes as following:
 -k INT               : initial k-mer size (default 32)
 -K FLOAT             : maximum-k-mer factor (maximum-k = FLOAT*read-length, default  0.5)
 
if your reads are 151bp, perhaps a -K 0.9 would be better, but I'm afraid that this will not make a big difference relative to the current result that you have, but perhaps is worth trying. Another option is to start with the long-reads, perhaps using the flye assembler, and then purge the heterozygous contigs with purge_dups or hapSolo. Starting with the long-reads might be advantageous as long-read overlap can be computed and therefore more bubbles (main graph pattern found in heterozygous genomes) can be spanned.
 Unfortunately,  Wengan is not well suited for highly heterozygous genomes and is a thing that I plan to work in but in the future (next year).
 
Best,
 Alex
