### ISSUE TITLE
WENGAN performance!!

### ISSUE THREAD

**Issue by Hai1983** [adigenova/wengan#55]
Hi !
I try to use the Wengan with the following configuration:
/home/users/d/a/daomhai/wengan-v0.2-bin-Linux/wengan.pl -x pacraw -a A -s bactpe.fwd.fastq.gz,bactpe.rev.fastq.gz -b hifi.fastq.gz -p asm2 -t 20 -g 3000. 

But it doesn't work, with the feedback is"  /home/users/d/a/daomhai/wengan-v0.2-bin-Linux/wengan.pl -h for detailed usage information."

Please help me overcome this issue.
Many thanks.

**Comment by adigenova** [comment]
Hi,
Are you able to run Wengan using the demo dataset?, the dataset is [here](https://github.com/adigenova/wengan_demo)
Best,
Alex

**Comment by Hai1983** [comment]
Dear Alex,

Thanks for your reply.
I will do that.

Sincerely,
Hai
