### ISSUE TITLE
longreads error

### ISSUE THREAD

**Issue by josieparis** [adigenova/wengan#56]
Hey Alex, 

I'm really impressed by all the hard work behind wengan! And am also really excited to use it to try and improve on an assembly I'm working on at the moment :)

I've installed wengan using singularity and am just trying to get through the demo (thanks for this demo!) to make sure everything is in place before I start on my much bigger (~2G) invertebrate genome assembly. 

So far I've tried wenganA and wenganM but both are failing with the following error in .err:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
make: *** [longreads./home/jrp228/programs/wengan-v0.2-bin-Linux/wengan_demo/ec_Wm_pr11.fa] Error 139
```
Here's the last couple of lines from .out prior to the crash:
```
/home/jrp228/programs/wengan-v0.2-bin-Linux/bin/fastmin-sg pacraw -k 15 -w 5 -q 40 -m 150 -r 300 -t  10 -p /home/jrp228/programs/wengan-v0.2-bin-Linux/wengan_
demo/ec_Wm_pr1 -I  500,1000,2000,3000,4000,5000,6000,7000,8000,10000,15000,20000 /home/jrp228/programs/wengan-v0.2-bin-Linux/wengan_demo/ec_Wm_pr1.MBC7.msplit
.fa /home/jrp228/programs/wengan-v0.2-bin-Linux/wengan_demo/ec_Wm_pr1.fml.txt 2>/home/jrp228/programs/wengan-v0.2-bin-Linux/wengan_demo/ec_Wm_pr1.fml.err >/ho
me/jrp228/programs/wengan-v0.2-bin-Linux/wengan_demo/ec_Wm_pr1.fml.log
/home/jrp228/programs/wengan-v0.2-bin-Linux/wengan_demo/ec_Wm_pr1.mk:57: recipe for target 'longreads./home/jrp228/programs/wengan-v0.2-bin-Linux/wengan_demo/
ec_Wm_pr11.fa' failed
```

I'm on CentOS Linux release 7.9.2009 (Core). It's a shared HPC and the only module I have loaded is singularity v3.8

Thank you!

Josie

**Comment by josieparis** [comment]
Hi Alex, 

I found some time to look into which part was erroring out, and it's a seg fault with fastmin-sg:

```
fastmin-sg pacraw -k 15 -w 5 -q 40 -m 150 -r 300 -I 500,1000,2000 -t 1 $WG/wengan_demo/ec_Wa_pr1.abyss2.contigs.fa $WG/wengan_demo/ec_Wa_pr1.fml.im.txt
```

gives:
```
LOG: Mapping mode =pacraw H=1 k=15 w=5 L=2000 l=250 q=40 m=150 c=65 r=300 t=1 o=FM I=500,1000,2000 s=1
reference=$WG/wengan_demo/ec_Wa_pr1.abyss2.contigs.fa queryfile=$WG/wengan_demo/ec_Wa_pr1.fml.im.txt
Building contig index
[M::mm_idx_gen::1635231053.827*0.00] collected minimizers
[M::mm_idx_gen::1635231054.033*0.00] sorted minimizers
[M::mm_mapopt_update::1635231054.058*0.00] mid_occ = 14
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 1; #seq: 125
[M::mm_idx_stat::1635231054.075*0.00] distinct minimizers: 924321 (81.76% are singletons); average occurrences: 1.255; average spacing: 4.011
Index construction time: 0.490000 seconds for 125 target sequence(s)
Query file  = $WG/wengan_demo/ecoli/reads/EC.PAC.30X.fa.gz
Lib : $WG/wengan_demo/ec_Wa_pr1.im.1.I500.fm.sam
Lib : $WG/wengan_demo/ec_Wa_pr1.im.1.I1000.fm.sam
Lib : $WG/wengan_demo/ec_Wa_pr1.im.1.I2000.fm.sam
A total of 3 syntethic libraries will be created by FastMin-SG
Segmentation fault (core dumped)
```
Would you like me to cross-post this on the github for fastmin? 

Thanks, 
Josie

**Comment by adigenova** [comment]
Hi Josie,
Thank you for the detailed info about the error that you are experiencing, but this should not be happening. Can you share the exact singularity command that you are using to run Wengan?, sometimes is necessary to add additional flags to singularity to map properly the files within the container,  the issue #34 provides additional information regarding singularity flags.  Another test might be to run Wengan without singularity but using the [pre-compiled](https://github.com/adigenova/wengan/releases/download/v0.2/wengan-v0.2-bin-Linux.tar.gz) binaries. 
Let me know how it goes, 
Best,
Alex

**Comment by josieparis** [comment]
Hi Alex, 

I tried without singularity and unfortunately I still get a seg fault from fastmin-sg. Running the code line by line, it's coming down to this part:

```
fastmin-sg pacraw -k 15 -w 5 -q 40 -m 150 -r 300 -I 500,1000,2000 -t 1 $WG/ec_Wa_pr1.abyss2.contigs.fa $WG/ec_Wa_pr1.fml.im.txt
```
and erroring out with this:

```
LOG: Mapping mode =pacraw H=1 k=15 w=5 L=2000 l=250 q=40 m=150 c=65 r=300 t=1 o=FM I=500,1000,2000 s=1
reference=$WG/ec_Wa_pr1.abyss2.contigs.fa queryfile=$WG/ec_Wa_pr1.fml.im.txt
Building contig index
[M::mm_idx_gen::1635612713.945*0.00] collected minimizers
[M::mm_idx_gen::1635612714.085*0.00] sorted minimizers
[M::mm_mapopt_update::1635612714.104*0.00] mid_occ = 14
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 1; #seq: 125
[M::mm_idx_stat::1635612714.116*0.00] distinct minimizers: 924328 (81.76% are singletons); average occurrences: 1.255; average spacing: 4.011
Index construction time: 0.320000 seconds for 125 target sequence(s)
Query file  = $WG/ecoli/reads/EC.PAC.30X.fa.gz
Lib : $WG/ec_Wa_pr1.im.1.I500.fm.sam
Lib : $WG/ec_Wa_pr1.im.1.I1000.fm.sam
Lib : $WG/ec_Wa_pr1.im.1.I2000.fm.sam
A total of 3 syntethic libraries will be created by FastMin-SG
Segmentation fault
```

Just so you know, the line before with the short reads, works well without errors 

```
fastmin-sg shortr -c 30 -k 21 -w 10 -q 20 -r 50000 -t 1 $WG/ec_Wa_pr1.abyss2.contigs.fa $WG/c_Wa_pr1.fms.txt
```

Thank you!

**Comment by adigenova** [comment]
Hi Josie, 
Sorry for the delay in the response, I just have the time to run again all the demo tests, and I do not have any issue, but I remember that when fastmin-sg crash is due to corrupted fastq/fasta files (see issue #29), the md5sum of the wengan_demo reads should be:
```
#reads
9a7bb42c643e254e90f4cf0811d41b5c  ecoli/reads/EC.ONT.30X.fa.gz
be59eac5fa4644a682ec372d807bcc5e  ecoli/reads/EC.PAC.30X.fa.gz
bb9777fa3444b941dcac8a045be05905  ecoli/reads/EC.50X.R1.fastq.gz
a11ac2c59b1f9efeb5b81572f54e80e2  ecoli/reads/EC.50X.R2.fastq.gz
```
Can you check that you have the same MD5s? (md5sum command).

My commands were the followings:
```
singularity shell wengan_v0.2.sif
# WenganA
perl /wengan/wengan-v0.2-bin-Linux/wengan.pl -x pacraw -a A -s ecoli/reads/EC.50X.R1.fastq.gz,ecoli/reads/EC.50X.R2.fastq.gz -l ecoli/reads/EC.PAC.30X.fa.gz -p ec_Wa_pr1 -t 10 -g 5
``` 


Best,
Alex

**Comment by adigenova** [comment]
Feel free to reopen if you still have issues.

**Comment by ASLeonard** [comment]
So I'm not entirely sure what is happening as it is too bizarre, but I was running into the exact same segfault. I was trying subsampling my reads to see if anything was causing this issue, but it looks like the fix was to change the contents of *asm.fms.txt* from
```
/out/asm1.ccs /out/asm.ccs.ec.fa
```
to
```
asm1.ccs asm.ccs.ec.fa
```
and then run fastmin-sg from inside the prefixed out directory. Not sure if the slash is somehow causing issues or what, but it did seem to fix it.

Upon further inspection, it may be due to using a `/` as the start (or maybe at all) of the prefix, because the long read file is named
```
longreads.<prefix>asm1.ccs.fa
```
which becomes e.g. `longreads./out/asm1.ccs.fa` and may cause an error since that "directory" doesn't exist

**Comment by ASLeonard** [comment]
If this is causing the issue, it looks like the issue may from somewhere like [this](https://github.com/adigenova/wengan/blob/b71c72d4e3f7c9c8e0ca6314bfc9e1c44a839e4d/perl/Wengan/SSG/LG.pm#L87).

Not sure if there was a good reason, but it doesn't make as much sense to have the $prefix in the middle of the variable, as it would necessarily interrupt any directory structure. I believe swapping it to be $prefix + longreads+ .. would fix the error

**Comment by weiluwl** [comment]
I tried to modify the mk file and rerun the mk file (changing to $prefix + longreads + ...), but the seg fault (core dump) error still occur. When I compiled it locally, the run finished without any error. I believe the singularity image might have some problems.
