### ISSUE TITLE
short read assembly commands

### ISSUE THREAD

**Issue by JacobSnelling** [adigenova/wengan#57]
Hi there.  I was curious if you could illustrate how to use Wengan with only short reads?  You refer to this in the paper, but the instructions are lacking in the Wengan documentation.  I can successfully run WenganM, or WenganA, with either PacBio HiFi reads, or CLR reads, plus Illumina short reads, but if I leave out any of the long read presets (-x or -l ), nothing will work.  Our project recently sequenced 7 genomes using the Sequel II, with hifi reads, but we also sequenced another 100 genomes using the NovaSeq 6000 (roughly 40X to 100X coverage per individual).  Of course, I get the initial short read assemblies that I could use further (if I use HiFi reads from a closely related individual as a placebo for the long read presets), but the final polished assembly includes components of the unrelated long reads, correct? Outside of mapping and variant detection against the references we are developing, I'm looking for ways to assemble high confidence contigs from the NovaSeq data, and Wengan seems like a good fit for the process.  Thank you very much for your excellent work.

**Comment by adigenova** [comment]
Hi Jacob, 
If you check supplementary table 7 of the manuscript you will notice that when you have only-short read data, the best option is to assemble the short-reads with DiscovarDenovo, this short-read assembler is used by the WenganD mode. Therefore, I suggest assembling all the 100 short-read datasets with DiscovarDenovo first (N50 contig 20-80kb). Then, you can give this short-read assembly as input to wengan (-x D and -c disco.datasetX.fa), plus the nearest long-read data  (or a combination of the 7 datasets).  DiscovarDenovo is a bit greedy in terms of memory, so you should avoid exceeding more than 60X of short-read coverage. The specific command for running DiscovarDenovo should look like this:

```
/wengan/wengan-v0.2-bin-Linux/bin/DiscovarExp 
READS="dataX.fwd.fastq.gz,dataX.rev.fastq.gz" 
OUT_DIR=dataX NUM_THREADS=Y 
2> dataX.Disco_denovo.err > dataX.Disco_denovo.log
```

Best,

Alex

**Comment by bishopia** [comment]
Hi Jacob,
would you mind sharing the arguments you used for Hifi + short reads? I'm using the v0.2 container and am having trouble getting the combo to work.

**Comment by JacobSnelling** [comment]
Hey there,

Sure thing, I can do that.  I was working with Sequel I CLR reads for
testing this with all three short-read assemblers, but I've run successful
assemblies using the pacraw option with css Hifi reads using the same
options.  However, I have not gotten the pacccs option to function properly
as of yet.

perl wengan.pl -x pacraw -a M -s R1.fastq.gz,R2.fastq.gz -l
longreads.fastq.gz -p YOURasm -t 4 -g 384

Hope this helps.

--Jacob

**Comment by JacobSnelling** [comment]
Thank you Alex, that definitely helps getting DiscovarDenovo to run through
Wengan.  I've got a couple of kinks that I'm still working out, but so far
so good.

Best Regards,

Jacob
