### ISSUE TITLE
Assembly methods

### ISSUE THREAD

**Issue by OZTaekOppa** [adigenova/wengan#58]
Hi,

Thank you so much for developing this great program.
After reading the manual, I could not find the best option for my dataset (plant genome: 2n = ~3Gb)

FYI,
Illumina PE: 50X
Illumina MP: 2Kb ~ 10Kb
PacBio: ~60X
ONT: ~ 100X

I have already tested this data with Shasta (only PacBio + ONT), AllHiC, 3D-DNA and Juicer but am not fully satisfied.
So, I might try your program for the same dataset. 

While I was looking for a hybrid option (Illumina + PacBio + ONT), it was only for Illumina + PacBio or Illumina + ONT, respectively. Is there any chance I could use all data (Illumina + PacBio + ONT) as the hybrid option? If not, I am thinking about this option: "Hybrid long-read only assembly of PacBio Circular Consensus Sequence and Nanopore data with WenganM". 

Looking forward to your reply!

Kind regards,

Taek

**Comment by adigenova** [comment]
Hi Taek, 
You are right at the moment Wengan can combine short+ONT or short+PAC reads, but not short+ONT+PAC as is your case. 
You can try the HiFi + ONT, but at the moment this has been tested on highly homozygous genomes only. I hope to release in the near future a new version that might be more appropriate for combining two sequencing technologies.

Best,
Alex
