### ISSUE TITLE
No rule to make target 'asm.MBC1.msplit.cov.txt', needed by 'asm1.fa'.

### ISSUE THREAD

**Issue by sigau** [adigenova/wengan#59]
Hi ( I recreate the issues because I didn't see the notification before closing the #53 )

So I was trying to assemble a genome using wengan D using both short-reads and long-reads on a computer with 1To of ram and 45 cpu.

At one moment I get this error (a file that is needed for the creation of another one ) :
`make: *** No rule to make target 'Proasellus_coiffaiti_HYB_wangan_D_porechop_3kb.MBC1.msplit.cov.txt', needed by 'longreads.Proasellus_coiffaiti_HYB_wangan_D_porechop_3kb1.fa'.  Stop.
`

So I don't really know what I can do to correct this.

Thanks in advance

here the log, error, script, and make files :
[assembly_wengan_D_PC.e.txt](https://github.com/adigenova/wengan/files/7497285/assembly_wengan_D_PC.e.txt)
[assembly_wengan_PC.sh.txt](https://github.com/adigenova/wengan/files/7497286/assembly_wengan_PC.sh.txt)
[Proasellus_coiffaiti_HYB_wangan_D_porechop_3kb.Disco_denovo.log](https://github.com/adigenova/wengan/files/7497287/Proasellus_coiffaiti_HYB_wangan_D_porechop_3kb.Disco_denovo.log)
[Proasellus_coiffaiti_HYB_wangan_D_porechop_3kb.mk.txt](https://github.com/adigenova/wengan/files/7497288/Proasellus_coiffaiti_HYB_wangan_D_porechop_3kb.mk.txt)

**Comment by adigenova** [comment]
Take a look to the comment in the #53, it is indeed a small bug that you can skip by changing the prefix name to not contain "fa".
Best,
Alex
