### ISSUE TITLE
HiFi/short-read hybrid assembly

### ISSUE THREAD

**Issue by bishopia** [adigenova/wengan#60]
I'm interested in using wengan for hybrid de novo assembly using PacBio HiFi/CCS reads and Illumina short reads. Given the set of potential combinations for assembly in the README, I thought perhaps someone might have advice on parameter setting for this somewhat unique data pairing. Any help much appreciated. -ian

**Comment by adigenova** [comment]
Hi Ian, 

Unfortunately, this mode is not fully implemented yet. It's true that it might be interesting to mix Illumina with low coverage HiFi for instance, but I have not tested it. The best option is to give the HiFi data as raw pacbio reads, but modifying  some fastmin-sg parameters, then the command should look like this:
```
perl wengan.pl -x pacraw 
  -i 500,1000,2000,3000,4000,5000,6000,7000,8000,9000,10000,11000,12000,13000,14000,15000 \
 -a D \
 -s lib1.fwd.fastq.gz,lib1.rev.fastq.gz \
 -l hifi.fastq.gz -p asm1 -t <cores> -g <genome_size>

```

This will first build contigs using the whole short-read data and then scaffold the contigs and close the gaps with the HiFi data. In this way, the HiFi data will not be used in the first step (contig generation) but all the rest. 

Best,
Alex
