### ISSUE TITLE
Setting new tmp directory for intermediate files

### ISSUE THREAD

**Issue by jblandis** [adigenova/wengan#62]
Hi,

Is there a way to change the location of the tmp directory to somewhere other than /tmp on linux? That particular partition on my system is small and keeps getting filled up during the run resulting in a terminated job. I was hoping to write these temporary files somewhere else with more space, but the typical "export TMPDIR=/new/location" does not seem to work. Any suggestions?

**Comment by adigenova** [comment]
Hi,

See issue #16 where some solutions are provided for fix this issue.
Best,

Alex
