### ISSUE TITLE
asm1.minia.41.contigs.fa] Error 127

### ISSUE THREAD

**Issue by bio-informatician** [adigenova/wengan#64]
Hi @adigenova, 
I am using Wengen for short read files from Illumina and long read from Nanopore with the following command
`perl wengan/wengan.pl -x ontraw -a M -s raw_data/ET1291_R1.fastq.gz,raw_data/ET1291_R2.fastq.gz -l raw_data/ET1291_hac.fastq.gz -p asm1 -t 20 -g 3000`

I used both Docker and binary files to run this command, but unfortunately, the following error occurs:
wengan/bin/minia -in asm1.minia_reads.41.txt -kmer-size 41 -abundance-min 2 -out asm1.minia.41 -minimizer-size 10 -max-memory 5000 -nb-cores 20 2> asm1.minia.41.err > asm1.minia.41.log
asm1.mk:4: recipe for target 'asm1.minia.41.contigs.fa' failed
make: *** [asm1.minia.41.contigs.fa] Error 127

I also installed Minia, but nothing changed. I also searched for argument -p in your documents and help of the application, but I still have no idea about this argument and asm1/asm3/asm5!

Could you please give me a short description about -p option and this issue?

**Comment by bio-informatician** [comment]
After applying different settings, I found out -p is for an output file name, so I suggest you write it both in your help menu of the tool and in the .readme file. About the mentioned issue, the same problem is with M, D, and A. 
minia.log:
wengan/bin/minia: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by wengan/bin/minia)

DiscovarExp.log:
wengan/assemble.mk:4: recipe for target 'wengan/assemble.contigs-disco.fa' failed
make: *** [wengan/assemble.contigs-disco.fa] Error 1

**Comment by adigenova** [comment]
Hi @bio-informatician,
the -p is var is just a prefix for the output files, the M (Minia),D (Discovar), and A (Abyss) are the respective Wengan modes. These parameters are documented in the wengan.pl script here  :

https://github.com/adigenova/wengan/blob/b71c72d4e3f7c9c8e0ca6314bfc9e1c44a839e4d/wengan.pl#L103

It seems that the error is related to a lack of libraries in your machine.
Can you share the docker command that you are using for running Wengan?

Best,
Alex

**Comment by adigenova** [comment]
Feel free to reopen if you are able to provide the requested information.
