### ISSUE TITLE
Using error corrected long reads

### ISSUE THREAD

**Issue by rjg2186** [adigenova/wengan#66]
Hi @adigenova ,

We just started using wengan for our assembly. Based on the documentation, I can understand it used raw pacbio or nanpore long reads. Could you please let us know if it is fine to use error corrected pacbio long reads as well with same parameters ?
Thanks.

**Comment by adigenova** [comment]
Hi @rjg2186, 
is fine to use error-corrected long reads, but perhaps some parameters that are good to tune are:

-i 500,1000,2000,3000,4000,5000,6000,7000,8000,10000,15000,20000
-N 3

Best,
Alex

**Comment by rjg2186** [comment]
Thank you @adigenova .
