### ISSUE TITLE
Error 137

### ISSUE THREAD

**Issue by shadowind** [adigenova/wengan#67]
Hi 
I'm facing an error 137 while trying to do assembly, couldnt find too much information, would appreciate any help

The error I recieved: 
```
bash: line 1:  6785 Killed                  abyss-stack-size 65536 abyss-bloom-dbg -k96 -q3 --kc=3 -v -b1G -H4 -j30 sr/20071D-13-01_S45_L002_R1_001.fastq.g
z sr/20071D-13-01_S45_L002_R2_001.fastq.gz sr/20071D-13-02_S46_L002_R1_001.fastq.gz sr/20071D-13-02_S46_L002_R2_001.fastq.gz > ec_Wa_pr1.abyss2-1.fa
make[1]: *** [ec_Wa_pr1.abyss2-1.fa] Error 137
```

More log and error file: https://drive.google.com/file/d/1MUWrle3l4_nyhURF4wzdVtNpCJnxg5pi/view?usp=sharing

The command I ran:

```
export WG=$HOME/wengen/wengan-v0.2-bin-Linux/wengan.pl
export LR=$HOME/fastq/lr
export SR=$HOME/fastq/sr

perl ${WG} -x pacraw -a A -s ${SR}/20071D-13-01_S45_L002_R1_001.fastq.gz,${SR}/20071D-13-01_S45_L002_R2_001.fastq.gz,${SR}/20071D-13-02_S46_L002_R1_001.fastq.gz,${SR}/20071D-13-02_S46_L002_R2_001.fastq.gz -l ${LR}/m64284e_220320_125421.fastq.gz,${LR}/m64284e_220321_190548.fastq.gz,${LR}/m64284e_220326_230326.fastq.gz,${LR}/m64284e_220328_051513.fastq.gz -p ec_Wa_pr1 -t 20 -g 5
```

**Comment by adigenova** [comment]
Hi, 
It seems that your job was killed,, are you using a cluster to run the jobs?

Best
Alex

**Comment by shadowind** [comment]
thank you for the quick response. I'm using single m5.8xlarge aws instance, 128GB/32CPU. seems OOM. Is wengan support running distributed on cluster?

**Comment by adigenova** [comment]
Wengan can run in a single node of a cluster, we do not support MPI. It seems that the genome that you are assembly is very large, at least when looking at the Abyss log 
```
Assembled 49839000000 bp in 519156251 contigs
Assembled 49840000512 bp in 519166673 contigs
Assembled 49841017248 bp in 519177264 contigs
```
What is the size of the genome? I think that the problem was the running time, then it was killed by the scheduler.
Best
Alex

**Comment by shadowind** [comment]
Could be 
the long read and short reads are 130GB each
seperate into 4 files
