### ISSUE TITLE
Is adapter filtering needed?

### ISSUE THREAD

**Issue by andreaswallberg** [adigenova/wengan#68]
Dear @adigenova,

I wonder if long-read and short-read adapter filtering is necessary in the assembly pipeline or if super high frequency kmers derived from adapters are pretty much discarded anyway?

Cheers!

**Comment by adigenova** [comment]
HI Andreas, 

not at all, the adapter generate high freq k-mers which are discarded when building the Bruijn graph or when mapping the long-reads back. Most of the Wengan assembled bases come from short reads..

Best
Alex
