### ISSUE TITLE
Unhandled kmer size

### ISSUE THREAD

**Issue by ebarta** [adigenova/wengan#69]
Hi,

I am trying to run the following command line:
nohup  perl /usr/local/molbio/wengan/wengan.pl -x ccsont -a M -l /molbio/flatfiles/sakal/passreads.fq.gz -b /molbio/flatfiles/sakal/hifiinput.fasta.gz -p sakal_wengan_2 -t 40 -g 2600 -d 6 -D 2 > logs/wengan_ccsont_v1.log 2> logs/wengan_ccsont_v1.log &

Its a diploid mammalian genome (golden jackal)

Everything goes fine at the beginning, but later I get the following error message:

EXCEPTION: Failure because of unhandled kmer size 161

I see that the minia has several option, ut do not see how to pass them to the standalone program. For example by default it uses 5000 MByte of RAM only.

Also, what setup would you suggest if I have not only hifi a nanopore but only PCR free illumina reads?

Thanks in advance,

Endre

**Comment by adigenova** [comment]
Hi, 

It seems that you compiled the code and for enabling large k-mer sizes is necessary to give some flags to minia3. 
I suggest using directly the code with the provided docker container.  I do not understand your second question well, do you mean if you only have short-reads? in that case, you should use Discovar, if you mean that you have both short and ONT reads, then the best wengan mode is WenganD, especially for mammalian genomes.

Best
Alex
