### ISSUE TITLE
Crash after finding links between unitigs

### ISSUE THREAD

**Issue by andreaswallberg** [adigenova/wengan#7]
I ran Wengan in on a machine with 1TB RAM and 20 cores, using both Illumina short-reads and PromethION data and Minia3 assembler. After 1 day and 9 hours the process crashes after finding links between unitigs.

This is the bottom of asm1.minia.41.log:

```
step 1 pass 7                                   15:47:07     memory [current, maxRSS]: [16847, 70610] MB 
step 2 (91448815kmers/217943625extremities)        16:07:05     memory [current, maxRSS]: [20032, 70610] MB 
gathering links from disk                       16:32:06     memory [current, maxRSS]: [17727, 70610] MB 
Done finding links between unitigs              17:48:17     memory [current, maxRSS]: [7857, 70610] MB 
loading unitigs from disk to memory
Stats:
Number of unitigs: 2213985986
Average number of incoming/outcoming neighbors: 0.0/0.0
Total number of nucleotides in unitigs: 116610855409

Memory usage:
   23581 MB keys in incoming vector
   23600 MB keys in outcoming vector
   1019 MB keys in dag_incoming_map vector
   1017 MB keys in dag_outcoming_map vector
   31566 MB packed unitigs (incl. 2721 MB delimiters)
   16384 MB unitigs lengths
   8445 MB unitigs abundances
   527 MB deleted/visited bitvectors
Estimated total: 106143.5 MB
iterating on 3755914903 nodes on disk
unexpected error: li.unitig=4611686016299118776, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016283862430, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016343682979, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016344738064, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016332944866, unitig_deleted.size()=unexpected error: li.unitig=unexpected error: li.unitig=46116860163007477422213985986, unitig_deleted.size()=46116860163007218602213985986
, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016343714144, unitig_deleted.size()=2213985986

unexpected error: li.unitig=4611686016284879238, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016289026266, unitig_deleted.size()=2213985986
unexpected error: li.unitig=unexpected error: li.unitig=4611686016291656030, unitig_deleted.size()=22139859864611686016293551128
, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016332374618, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016312758977, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016311400272, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016335807901, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016311031310, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016292558110, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016311674943, unitig_deleted.size()=2213985986
unexpected error: li.unitig=4611686016289764357, unitig_deleted.size()=2213985986
```

This is the bottom of asm1.minia.41.log:

```
[Building BooPHF]  98.4 %   elapsed:   3 min 48 sec   remaining:   0 min 4  sec
[Building BooPHF]  98.5 %   elapsed:   3 min 49 sec   remaining:   0 min 3  sec

[removing tips,    pass  1               ]  0    %   elapsed:   0 min 0  sec   remaining:   0 min 0  sec   cpu:  -1.0 %   mem: [106828, 106828, 128825] MB *** Error in `/crex/proj/uppstore2018098/nobackup/andreas/devel/wengan/wengan-v0.1-bin-Linux/bin/minia': double free or corruption (!prev): 0x0000000002737040 ***
```

My own error log on the machine indicates that the program died with a segmentation fault. There is also peculiar "make" error:

`make: *** [<MYPATH>/asm1.minia.41.contigs.fa] Error 139`

I used the precompiled binaries to run Wengan.

This machine is a CentOS Linux 7 (Core) with gcc (GCC) 4.8.5 and GNU libc 2.17, which different from what was used to compile the tools that Wengan wraps around. To get Minia3 to start, I loaded a recent version of GCC (gcc/9.2.0) via our lmod system.

Was Wengan about to switch to a different binary at this point?
Could there be some GCC/glibc issue here?
Assuming the I can fix the issue, is it possible to resume the assembly at this point or do I have to restart it?

Cheers!

**Comment by adigenova** [comment]
Hi Andreas,

### Was Wengan about to switch to a different binary at this point?

No, Wengan implements a muli-kmer approach with Minia3, in particular, 41, 81 and 121. These k-mer sizes work well with human-sized genomes. For more complex genomes (>4Gb),  I think is necessary to go for larger k-mer sizes (i.e 41,81,121,161,201,241,281,321) and give more cores (i.e 40). The larger k-mers need error-corrected short-reads ( i.e BFC: https://github.com/lh3/bfc), thus for complex genomes, some sequencing strategy and software tunning is necessary. Moreover, the current wengan version supports a maximum genome size of 4Gb, I'll fix that soon, but for the moment wengan is not available for genomes >4Gb (I'll add a limitation section in the readme file).

### Could there be some GCC/glibc issue here?
To have access to larger k-mers sizes is necessary to re-compile the minia code (check their manuals), then you can modify the run-minia.pl script available on the aux_script of wengan distribution and add the larger k-mers. Notice that your larger k-mer size is constrained by the read length, for instance with 250bp reads you can use a k-mer size up to 200bp.

### Assuming the I can fix the issue, is it possible to resume the assembly at this point or do I have to restart it?
No, minia crashed in the first k-mer size iteration.

I think that a possible strategy is to try to achieve a good Minia assembly first (i.e N50 > 5kb). 

Best,
 
Alex
