### ISSUE TITLE
issues with non IUPAC bases

### ISSUE THREAD

**Issue by gargkritika** [adigenova/wengan#70]
Hi Alex,

Thank you for the wonderful program. I am getting the non-IUPAC base error for liger. Based on your previous comments, I installed the seqtk, based on your fork. However, I cannot find the option 'iupac2basesA' 

Please suggest a solution for this error.

Thank you
Best regards
Kritika

**Comment by adigenova** [comment]
Hi Kritika, 
The required step for fixing your issue are:

```
git clone https://github.com/adigenova/seqtk.git
cd seqtk
make 
```
then you will have the function iupac2basesA

Best
Alex
