### ISSUE TITLE
unrecognized command 'iupac2bases'. Abort!

### ISSUE THREAD

**Issue by mergi-2674** [adigenova/wengan#71]
Hio @adigenova 
I was running wenganA on my data set. After it went well it gave me an error report which says:

[main] unrecognized command 'iupac2bases'. Abort!
[E::stk_cutN] failed to open the input file/stream.

I tried to make seqtk from github and the same error appears.
How it get fixed?

Best,

**Comment by adigenova** [comment]
HI, 

the issue #47 address this specific question.

Best
Alex
