### ISSUE TITLE
Installatation

### ISSUE THREAD

**Issue by bioramg** [adigenova/wengan#72]
Hello Sir,
I would like to assemble the plant mitochondrial genome using both Illumina and Nanopore reads. I am very basic to Linux. I could not find out the installation steps in the file. Could you please give me the steps for the installation process?

**Comment by adigenova** [comment]
Hi bioramg, 

The most easy way is to download the precompiled binaries available on the release page. 
Additionally, there is a container in docker that provide the binaries, which can also be used from singularity. 
We plan to release soon a version compatible with conda or bioconda.


Best,
Alex
