### ISSUE TITLE
Leveraging ONT raw and PacBio raw

### ISSUE THREAD

**Issue by 000generic** [adigenova/wengan#74]
Hi!

I'm very interested / excited to try WENGAN out to assemble human-sized+ cephalopod genomes. I was wondering if there is a preset or recommended strategy for using WENGAN with data sets that include Illumina, ONT, and PacBio. 

Thank you :) 
Eric

**Comment by adigenova** [comment]
Hi, 

You can merge ONT+Pacbio in a single file and then run the pipeline using the settings for ONT. It will definitely improve the consensus of the edges. 

Best
Alex
