### ISSUE TITLE
Wengan paper short read assemblies

### ISSUE THREAD

**Issue by kevyin** [adigenova/wengan#8]
Hi Thanks for wengan
Am eager to try wengan on our data but the DISCOVAR DENOVO  memory seems to be quite high
Was wondering if any of the short read NA24385/NA12878 DISCOVAR DENOVO assemblies are available anywhere for download?

Cheers,
Kevin

**Comment by adigenova** [comment]
Hi Kevin,
The discovar assembly of NA24385 and NA12878 can be downloaded from zenodo:
## NA12878 
https://zenodo.org/record/2598666/files/NA12878.ILL250.DISCOVAR.fa.gz
## NA24385
https://zenodo.org/record/2598666/files/NA24385.ILL250.DISCOVAR.fa.gz

all the Wengan assemblies described in the ms are available in the Zenodo repo:
## Zenodo
https://zenodo.org/record/2598666
